package skyline.platform.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PtdeptExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    public PtdeptExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDeptidIsNull() {
            addCriterion("DEPTID is null");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNotNull() {
            addCriterion("DEPTID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptidEqualTo(String value) {
            addCriterion("DEPTID =", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotEqualTo(String value) {
            addCriterion("DEPTID <>", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThan(String value) {
            addCriterion("DEPTID >", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThanOrEqualTo(String value) {
            addCriterion("DEPTID >=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThan(String value) {
            addCriterion("DEPTID <", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThanOrEqualTo(String value) {
            addCriterion("DEPTID <=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLike(String value) {
            addCriterion("DEPTID like", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotLike(String value) {
            addCriterion("DEPTID not like", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidIn(List<String> values) {
            addCriterion("DEPTID in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotIn(List<String> values) {
            addCriterion("DEPTID not in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidBetween(String value1, String value2) {
            addCriterion("DEPTID between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotBetween(String value1, String value2) {
            addCriterion("DEPTID not between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptnameIsNull() {
            addCriterion("DEPTNAME is null");
            return (Criteria) this;
        }

        public Criteria andDeptnameIsNotNull() {
            addCriterion("DEPTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andDeptnameEqualTo(String value) {
            addCriterion("DEPTNAME =", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameNotEqualTo(String value) {
            addCriterion("DEPTNAME <>", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameGreaterThan(String value) {
            addCriterion("DEPTNAME >", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameGreaterThanOrEqualTo(String value) {
            addCriterion("DEPTNAME >=", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameLessThan(String value) {
            addCriterion("DEPTNAME <", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameLessThanOrEqualTo(String value) {
            addCriterion("DEPTNAME <=", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameLike(String value) {
            addCriterion("DEPTNAME like", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameNotLike(String value) {
            addCriterion("DEPTNAME not like", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameIn(List<String> values) {
            addCriterion("DEPTNAME in", values, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameNotIn(List<String> values) {
            addCriterion("DEPTNAME not in", values, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameBetween(String value1, String value2) {
            addCriterion("DEPTNAME between", value1, value2, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameNotBetween(String value1, String value2) {
            addCriterion("DEPTNAME not between", value1, value2, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptdescIsNull() {
            addCriterion("DEPTDESC is null");
            return (Criteria) this;
        }

        public Criteria andDeptdescIsNotNull() {
            addCriterion("DEPTDESC is not null");
            return (Criteria) this;
        }

        public Criteria andDeptdescEqualTo(String value) {
            addCriterion("DEPTDESC =", value, "deptdesc");
            return (Criteria) this;
        }

        public Criteria andDeptdescNotEqualTo(String value) {
            addCriterion("DEPTDESC <>", value, "deptdesc");
            return (Criteria) this;
        }

        public Criteria andDeptdescGreaterThan(String value) {
            addCriterion("DEPTDESC >", value, "deptdesc");
            return (Criteria) this;
        }

        public Criteria andDeptdescGreaterThanOrEqualTo(String value) {
            addCriterion("DEPTDESC >=", value, "deptdesc");
            return (Criteria) this;
        }

        public Criteria andDeptdescLessThan(String value) {
            addCriterion("DEPTDESC <", value, "deptdesc");
            return (Criteria) this;
        }

        public Criteria andDeptdescLessThanOrEqualTo(String value) {
            addCriterion("DEPTDESC <=", value, "deptdesc");
            return (Criteria) this;
        }

        public Criteria andDeptdescLike(String value) {
            addCriterion("DEPTDESC like", value, "deptdesc");
            return (Criteria) this;
        }

        public Criteria andDeptdescNotLike(String value) {
            addCriterion("DEPTDESC not like", value, "deptdesc");
            return (Criteria) this;
        }

        public Criteria andDeptdescIn(List<String> values) {
            addCriterion("DEPTDESC in", values, "deptdesc");
            return (Criteria) this;
        }

        public Criteria andDeptdescNotIn(List<String> values) {
            addCriterion("DEPTDESC not in", values, "deptdesc");
            return (Criteria) this;
        }

        public Criteria andDeptdescBetween(String value1, String value2) {
            addCriterion("DEPTDESC between", value1, value2, "deptdesc");
            return (Criteria) this;
        }

        public Criteria andDeptdescNotBetween(String value1, String value2) {
            addCriterion("DEPTDESC not between", value1, value2, "deptdesc");
            return (Criteria) this;
        }

        public Criteria andParentdeptidIsNull() {
            addCriterion("PARENTDEPTID is null");
            return (Criteria) this;
        }

        public Criteria andParentdeptidIsNotNull() {
            addCriterion("PARENTDEPTID is not null");
            return (Criteria) this;
        }

        public Criteria andParentdeptidEqualTo(String value) {
            addCriterion("PARENTDEPTID =", value, "parentdeptid");
            return (Criteria) this;
        }

        public Criteria andParentdeptidNotEqualTo(String value) {
            addCriterion("PARENTDEPTID <>", value, "parentdeptid");
            return (Criteria) this;
        }

        public Criteria andParentdeptidGreaterThan(String value) {
            addCriterion("PARENTDEPTID >", value, "parentdeptid");
            return (Criteria) this;
        }

        public Criteria andParentdeptidGreaterThanOrEqualTo(String value) {
            addCriterion("PARENTDEPTID >=", value, "parentdeptid");
            return (Criteria) this;
        }

        public Criteria andParentdeptidLessThan(String value) {
            addCriterion("PARENTDEPTID <", value, "parentdeptid");
            return (Criteria) this;
        }

        public Criteria andParentdeptidLessThanOrEqualTo(String value) {
            addCriterion("PARENTDEPTID <=", value, "parentdeptid");
            return (Criteria) this;
        }

        public Criteria andParentdeptidLike(String value) {
            addCriterion("PARENTDEPTID like", value, "parentdeptid");
            return (Criteria) this;
        }

        public Criteria andParentdeptidNotLike(String value) {
            addCriterion("PARENTDEPTID not like", value, "parentdeptid");
            return (Criteria) this;
        }

        public Criteria andParentdeptidIn(List<String> values) {
            addCriterion("PARENTDEPTID in", values, "parentdeptid");
            return (Criteria) this;
        }

        public Criteria andParentdeptidNotIn(List<String> values) {
            addCriterion("PARENTDEPTID not in", values, "parentdeptid");
            return (Criteria) this;
        }

        public Criteria andParentdeptidBetween(String value1, String value2) {
            addCriterion("PARENTDEPTID between", value1, value2, "parentdeptid");
            return (Criteria) this;
        }

        public Criteria andParentdeptidNotBetween(String value1, String value2) {
            addCriterion("PARENTDEPTID not between", value1, value2, "parentdeptid");
            return (Criteria) this;
        }

        public Criteria andDeptleafIsNull() {
            addCriterion("DEPTLEAF is null");
            return (Criteria) this;
        }

        public Criteria andDeptleafIsNotNull() {
            addCriterion("DEPTLEAF is not null");
            return (Criteria) this;
        }

        public Criteria andDeptleafEqualTo(String value) {
            addCriterion("DEPTLEAF =", value, "deptleaf");
            return (Criteria) this;
        }

        public Criteria andDeptleafNotEqualTo(String value) {
            addCriterion("DEPTLEAF <>", value, "deptleaf");
            return (Criteria) this;
        }

        public Criteria andDeptleafGreaterThan(String value) {
            addCriterion("DEPTLEAF >", value, "deptleaf");
            return (Criteria) this;
        }

        public Criteria andDeptleafGreaterThanOrEqualTo(String value) {
            addCriterion("DEPTLEAF >=", value, "deptleaf");
            return (Criteria) this;
        }

        public Criteria andDeptleafLessThan(String value) {
            addCriterion("DEPTLEAF <", value, "deptleaf");
            return (Criteria) this;
        }

        public Criteria andDeptleafLessThanOrEqualTo(String value) {
            addCriterion("DEPTLEAF <=", value, "deptleaf");
            return (Criteria) this;
        }

        public Criteria andDeptleafLike(String value) {
            addCriterion("DEPTLEAF like", value, "deptleaf");
            return (Criteria) this;
        }

        public Criteria andDeptleafNotLike(String value) {
            addCriterion("DEPTLEAF not like", value, "deptleaf");
            return (Criteria) this;
        }

        public Criteria andDeptleafIn(List<String> values) {
            addCriterion("DEPTLEAF in", values, "deptleaf");
            return (Criteria) this;
        }

        public Criteria andDeptleafNotIn(List<String> values) {
            addCriterion("DEPTLEAF not in", values, "deptleaf");
            return (Criteria) this;
        }

        public Criteria andDeptleafBetween(String value1, String value2) {
            addCriterion("DEPTLEAF between", value1, value2, "deptleaf");
            return (Criteria) this;
        }

        public Criteria andDeptleafNotBetween(String value1, String value2) {
            addCriterion("DEPTLEAF not between", value1, value2, "deptleaf");
            return (Criteria) this;
        }

        public Criteria andDeptlevelIsNull() {
            addCriterion("DEPTLEVEL is null");
            return (Criteria) this;
        }

        public Criteria andDeptlevelIsNotNull() {
            addCriterion("DEPTLEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andDeptlevelEqualTo(Short value) {
            addCriterion("DEPTLEVEL =", value, "deptlevel");
            return (Criteria) this;
        }

        public Criteria andDeptlevelNotEqualTo(Short value) {
            addCriterion("DEPTLEVEL <>", value, "deptlevel");
            return (Criteria) this;
        }

        public Criteria andDeptlevelGreaterThan(Short value) {
            addCriterion("DEPTLEVEL >", value, "deptlevel");
            return (Criteria) this;
        }

        public Criteria andDeptlevelGreaterThanOrEqualTo(Short value) {
            addCriterion("DEPTLEVEL >=", value, "deptlevel");
            return (Criteria) this;
        }

        public Criteria andDeptlevelLessThan(Short value) {
            addCriterion("DEPTLEVEL <", value, "deptlevel");
            return (Criteria) this;
        }

        public Criteria andDeptlevelLessThanOrEqualTo(Short value) {
            addCriterion("DEPTLEVEL <=", value, "deptlevel");
            return (Criteria) this;
        }

        public Criteria andDeptlevelIn(List<Short> values) {
            addCriterion("DEPTLEVEL in", values, "deptlevel");
            return (Criteria) this;
        }

        public Criteria andDeptlevelNotIn(List<Short> values) {
            addCriterion("DEPTLEVEL not in", values, "deptlevel");
            return (Criteria) this;
        }

        public Criteria andDeptlevelBetween(Short value1, Short value2) {
            addCriterion("DEPTLEVEL between", value1, value2, "deptlevel");
            return (Criteria) this;
        }

        public Criteria andDeptlevelNotBetween(Short value1, Short value2) {
            addCriterion("DEPTLEVEL not between", value1, value2, "deptlevel");
            return (Criteria) this;
        }

        public Criteria andDeptstatusIsNull() {
            addCriterion("DEPTSTATUS is null");
            return (Criteria) this;
        }

        public Criteria andDeptstatusIsNotNull() {
            addCriterion("DEPTSTATUS is not null");
            return (Criteria) this;
        }

        public Criteria andDeptstatusEqualTo(String value) {
            addCriterion("DEPTSTATUS =", value, "deptstatus");
            return (Criteria) this;
        }

        public Criteria andDeptstatusNotEqualTo(String value) {
            addCriterion("DEPTSTATUS <>", value, "deptstatus");
            return (Criteria) this;
        }

        public Criteria andDeptstatusGreaterThan(String value) {
            addCriterion("DEPTSTATUS >", value, "deptstatus");
            return (Criteria) this;
        }

        public Criteria andDeptstatusGreaterThanOrEqualTo(String value) {
            addCriterion("DEPTSTATUS >=", value, "deptstatus");
            return (Criteria) this;
        }

        public Criteria andDeptstatusLessThan(String value) {
            addCriterion("DEPTSTATUS <", value, "deptstatus");
            return (Criteria) this;
        }

        public Criteria andDeptstatusLessThanOrEqualTo(String value) {
            addCriterion("DEPTSTATUS <=", value, "deptstatus");
            return (Criteria) this;
        }

        public Criteria andDeptstatusLike(String value) {
            addCriterion("DEPTSTATUS like", value, "deptstatus");
            return (Criteria) this;
        }

        public Criteria andDeptstatusNotLike(String value) {
            addCriterion("DEPTSTATUS not like", value, "deptstatus");
            return (Criteria) this;
        }

        public Criteria andDeptstatusIn(List<String> values) {
            addCriterion("DEPTSTATUS in", values, "deptstatus");
            return (Criteria) this;
        }

        public Criteria andDeptstatusNotIn(List<String> values) {
            addCriterion("DEPTSTATUS not in", values, "deptstatus");
            return (Criteria) this;
        }

        public Criteria andDeptstatusBetween(String value1, String value2) {
            addCriterion("DEPTSTATUS between", value1, value2, "deptstatus");
            return (Criteria) this;
        }

        public Criteria andDeptstatusNotBetween(String value1, String value2) {
            addCriterion("DEPTSTATUS not between", value1, value2, "deptstatus");
            return (Criteria) this;
        }

        public Criteria andIsdummyIsNull() {
            addCriterion("ISDUMMY is null");
            return (Criteria) this;
        }

        public Criteria andIsdummyIsNotNull() {
            addCriterion("ISDUMMY is not null");
            return (Criteria) this;
        }

        public Criteria andIsdummyEqualTo(String value) {
            addCriterion("ISDUMMY =", value, "isdummy");
            return (Criteria) this;
        }

        public Criteria andIsdummyNotEqualTo(String value) {
            addCriterion("ISDUMMY <>", value, "isdummy");
            return (Criteria) this;
        }

        public Criteria andIsdummyGreaterThan(String value) {
            addCriterion("ISDUMMY >", value, "isdummy");
            return (Criteria) this;
        }

        public Criteria andIsdummyGreaterThanOrEqualTo(String value) {
            addCriterion("ISDUMMY >=", value, "isdummy");
            return (Criteria) this;
        }

        public Criteria andIsdummyLessThan(String value) {
            addCriterion("ISDUMMY <", value, "isdummy");
            return (Criteria) this;
        }

        public Criteria andIsdummyLessThanOrEqualTo(String value) {
            addCriterion("ISDUMMY <=", value, "isdummy");
            return (Criteria) this;
        }

        public Criteria andIsdummyLike(String value) {
            addCriterion("ISDUMMY like", value, "isdummy");
            return (Criteria) this;
        }

        public Criteria andIsdummyNotLike(String value) {
            addCriterion("ISDUMMY not like", value, "isdummy");
            return (Criteria) this;
        }

        public Criteria andIsdummyIn(List<String> values) {
            addCriterion("ISDUMMY in", values, "isdummy");
            return (Criteria) this;
        }

        public Criteria andIsdummyNotIn(List<String> values) {
            addCriterion("ISDUMMY not in", values, "isdummy");
            return (Criteria) this;
        }

        public Criteria andIsdummyBetween(String value1, String value2) {
            addCriterion("ISDUMMY between", value1, value2, "isdummy");
            return (Criteria) this;
        }

        public Criteria andIsdummyNotBetween(String value1, String value2) {
            addCriterion("ISDUMMY not between", value1, value2, "isdummy");
            return (Criteria) this;
        }

        public Criteria andFillstr10IsNull() {
            addCriterion("FILLSTR10 is null");
            return (Criteria) this;
        }

        public Criteria andFillstr10IsNotNull() {
            addCriterion("FILLSTR10 is not null");
            return (Criteria) this;
        }

        public Criteria andFillstr10EqualTo(String value) {
            addCriterion("FILLSTR10 =", value, "fillstr10");
            return (Criteria) this;
        }

        public Criteria andFillstr10NotEqualTo(String value) {
            addCriterion("FILLSTR10 <>", value, "fillstr10");
            return (Criteria) this;
        }

        public Criteria andFillstr10GreaterThan(String value) {
            addCriterion("FILLSTR10 >", value, "fillstr10");
            return (Criteria) this;
        }

        public Criteria andFillstr10GreaterThanOrEqualTo(String value) {
            addCriterion("FILLSTR10 >=", value, "fillstr10");
            return (Criteria) this;
        }

        public Criteria andFillstr10LessThan(String value) {
            addCriterion("FILLSTR10 <", value, "fillstr10");
            return (Criteria) this;
        }

        public Criteria andFillstr10LessThanOrEqualTo(String value) {
            addCriterion("FILLSTR10 <=", value, "fillstr10");
            return (Criteria) this;
        }

        public Criteria andFillstr10Like(String value) {
            addCriterion("FILLSTR10 like", value, "fillstr10");
            return (Criteria) this;
        }

        public Criteria andFillstr10NotLike(String value) {
            addCriterion("FILLSTR10 not like", value, "fillstr10");
            return (Criteria) this;
        }

        public Criteria andFillstr10In(List<String> values) {
            addCriterion("FILLSTR10 in", values, "fillstr10");
            return (Criteria) this;
        }

        public Criteria andFillstr10NotIn(List<String> values) {
            addCriterion("FILLSTR10 not in", values, "fillstr10");
            return (Criteria) this;
        }

        public Criteria andFillstr10Between(String value1, String value2) {
            addCriterion("FILLSTR10 between", value1, value2, "fillstr10");
            return (Criteria) this;
        }

        public Criteria andFillstr10NotBetween(String value1, String value2) {
            addCriterion("FILLSTR10 not between", value1, value2, "fillstr10");
            return (Criteria) this;
        }

        public Criteria andFillstr20IsNull() {
            addCriterion("FILLSTR20 is null");
            return (Criteria) this;
        }

        public Criteria andFillstr20IsNotNull() {
            addCriterion("FILLSTR20 is not null");
            return (Criteria) this;
        }

        public Criteria andFillstr20EqualTo(String value) {
            addCriterion("FILLSTR20 =", value, "fillstr20");
            return (Criteria) this;
        }

        public Criteria andFillstr20NotEqualTo(String value) {
            addCriterion("FILLSTR20 <>", value, "fillstr20");
            return (Criteria) this;
        }

        public Criteria andFillstr20GreaterThan(String value) {
            addCriterion("FILLSTR20 >", value, "fillstr20");
            return (Criteria) this;
        }

        public Criteria andFillstr20GreaterThanOrEqualTo(String value) {
            addCriterion("FILLSTR20 >=", value, "fillstr20");
            return (Criteria) this;
        }

        public Criteria andFillstr20LessThan(String value) {
            addCriterion("FILLSTR20 <", value, "fillstr20");
            return (Criteria) this;
        }

        public Criteria andFillstr20LessThanOrEqualTo(String value) {
            addCriterion("FILLSTR20 <=", value, "fillstr20");
            return (Criteria) this;
        }

        public Criteria andFillstr20Like(String value) {
            addCriterion("FILLSTR20 like", value, "fillstr20");
            return (Criteria) this;
        }

        public Criteria andFillstr20NotLike(String value) {
            addCriterion("FILLSTR20 not like", value, "fillstr20");
            return (Criteria) this;
        }

        public Criteria andFillstr20In(List<String> values) {
            addCriterion("FILLSTR20 in", values, "fillstr20");
            return (Criteria) this;
        }

        public Criteria andFillstr20NotIn(List<String> values) {
            addCriterion("FILLSTR20 not in", values, "fillstr20");
            return (Criteria) this;
        }

        public Criteria andFillstr20Between(String value1, String value2) {
            addCriterion("FILLSTR20 between", value1, value2, "fillstr20");
            return (Criteria) this;
        }

        public Criteria andFillstr20NotBetween(String value1, String value2) {
            addCriterion("FILLSTR20 not between", value1, value2, "fillstr20");
            return (Criteria) this;
        }

        public Criteria andFillstr100IsNull() {
            addCriterion("FILLSTR100 is null");
            return (Criteria) this;
        }

        public Criteria andFillstr100IsNotNull() {
            addCriterion("FILLSTR100 is not null");
            return (Criteria) this;
        }

        public Criteria andFillstr100EqualTo(String value) {
            addCriterion("FILLSTR100 =", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100NotEqualTo(String value) {
            addCriterion("FILLSTR100 <>", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100GreaterThan(String value) {
            addCriterion("FILLSTR100 >", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100GreaterThanOrEqualTo(String value) {
            addCriterion("FILLSTR100 >=", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100LessThan(String value) {
            addCriterion("FILLSTR100 <", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100LessThanOrEqualTo(String value) {
            addCriterion("FILLSTR100 <=", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100Like(String value) {
            addCriterion("FILLSTR100 like", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100NotLike(String value) {
            addCriterion("FILLSTR100 not like", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100In(List<String> values) {
            addCriterion("FILLSTR100 in", values, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100NotIn(List<String> values) {
            addCriterion("FILLSTR100 not in", values, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100Between(String value1, String value2) {
            addCriterion("FILLSTR100 between", value1, value2, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100NotBetween(String value1, String value2) {
            addCriterion("FILLSTR100 not between", value1, value2, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr150IsNull() {
            addCriterion("FILLSTR150 is null");
            return (Criteria) this;
        }

        public Criteria andFillstr150IsNotNull() {
            addCriterion("FILLSTR150 is not null");
            return (Criteria) this;
        }

        public Criteria andFillstr150EqualTo(String value) {
            addCriterion("FILLSTR150 =", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150NotEqualTo(String value) {
            addCriterion("FILLSTR150 <>", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150GreaterThan(String value) {
            addCriterion("FILLSTR150 >", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150GreaterThanOrEqualTo(String value) {
            addCriterion("FILLSTR150 >=", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150LessThan(String value) {
            addCriterion("FILLSTR150 <", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150LessThanOrEqualTo(String value) {
            addCriterion("FILLSTR150 <=", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150Like(String value) {
            addCriterion("FILLSTR150 like", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150NotLike(String value) {
            addCriterion("FILLSTR150 not like", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150In(List<String> values) {
            addCriterion("FILLSTR150 in", values, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150NotIn(List<String> values) {
            addCriterion("FILLSTR150 not in", values, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150Between(String value1, String value2) {
            addCriterion("FILLSTR150 between", value1, value2, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150NotBetween(String value1, String value2) {
            addCriterion("FILLSTR150 not between", value1, value2, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillint4IsNull() {
            addCriterion("FILLINT4 is null");
            return (Criteria) this;
        }

        public Criteria andFillint4IsNotNull() {
            addCriterion("FILLINT4 is not null");
            return (Criteria) this;
        }

        public Criteria andFillint4EqualTo(Short value) {
            addCriterion("FILLINT4 =", value, "fillint4");
            return (Criteria) this;
        }

        public Criteria andFillint4NotEqualTo(Short value) {
            addCriterion("FILLINT4 <>", value, "fillint4");
            return (Criteria) this;
        }

        public Criteria andFillint4GreaterThan(Short value) {
            addCriterion("FILLINT4 >", value, "fillint4");
            return (Criteria) this;
        }

        public Criteria andFillint4GreaterThanOrEqualTo(Short value) {
            addCriterion("FILLINT4 >=", value, "fillint4");
            return (Criteria) this;
        }

        public Criteria andFillint4LessThan(Short value) {
            addCriterion("FILLINT4 <", value, "fillint4");
            return (Criteria) this;
        }

        public Criteria andFillint4LessThanOrEqualTo(Short value) {
            addCriterion("FILLINT4 <=", value, "fillint4");
            return (Criteria) this;
        }

        public Criteria andFillint4In(List<Short> values) {
            addCriterion("FILLINT4 in", values, "fillint4");
            return (Criteria) this;
        }

        public Criteria andFillint4NotIn(List<Short> values) {
            addCriterion("FILLINT4 not in", values, "fillint4");
            return (Criteria) this;
        }

        public Criteria andFillint4Between(Short value1, Short value2) {
            addCriterion("FILLINT4 between", value1, value2, "fillint4");
            return (Criteria) this;
        }

        public Criteria andFillint4NotBetween(Short value1, Short value2) {
            addCriterion("FILLINT4 not between", value1, value2, "fillint4");
            return (Criteria) this;
        }

        public Criteria andFillint6IsNull() {
            addCriterion("FILLINT6 is null");
            return (Criteria) this;
        }

        public Criteria andFillint6IsNotNull() {
            addCriterion("FILLINT6 is not null");
            return (Criteria) this;
        }

        public Criteria andFillint6EqualTo(Integer value) {
            addCriterion("FILLINT6 =", value, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6NotEqualTo(Integer value) {
            addCriterion("FILLINT6 <>", value, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6GreaterThan(Integer value) {
            addCriterion("FILLINT6 >", value, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6GreaterThanOrEqualTo(Integer value) {
            addCriterion("FILLINT6 >=", value, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6LessThan(Integer value) {
            addCriterion("FILLINT6 <", value, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6LessThanOrEqualTo(Integer value) {
            addCriterion("FILLINT6 <=", value, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6In(List<Integer> values) {
            addCriterion("FILLINT6 in", values, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6NotIn(List<Integer> values) {
            addCriterion("FILLINT6 not in", values, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6Between(Integer value1, Integer value2) {
            addCriterion("FILLINT6 between", value1, value2, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6NotBetween(Integer value1, Integer value2) {
            addCriterion("FILLINT6 not between", value1, value2, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint8IsNull() {
            addCriterion("FILLINT8 is null");
            return (Criteria) this;
        }

        public Criteria andFillint8IsNotNull() {
            addCriterion("FILLINT8 is not null");
            return (Criteria) this;
        }

        public Criteria andFillint8EqualTo(Integer value) {
            addCriterion("FILLINT8 =", value, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8NotEqualTo(Integer value) {
            addCriterion("FILLINT8 <>", value, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8GreaterThan(Integer value) {
            addCriterion("FILLINT8 >", value, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8GreaterThanOrEqualTo(Integer value) {
            addCriterion("FILLINT8 >=", value, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8LessThan(Integer value) {
            addCriterion("FILLINT8 <", value, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8LessThanOrEqualTo(Integer value) {
            addCriterion("FILLINT8 <=", value, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8In(List<Integer> values) {
            addCriterion("FILLINT8 in", values, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8NotIn(List<Integer> values) {
            addCriterion("FILLINT8 not in", values, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8Between(Integer value1, Integer value2) {
            addCriterion("FILLINT8 between", value1, value2, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8NotBetween(Integer value1, Integer value2) {
            addCriterion("FILLINT8 not between", value1, value2, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFilldbl2IsNull() {
            addCriterion("FILLDBL2 is null");
            return (Criteria) this;
        }

        public Criteria andFilldbl2IsNotNull() {
            addCriterion("FILLDBL2 is not null");
            return (Criteria) this;
        }

        public Criteria andFilldbl2EqualTo(BigDecimal value) {
            addCriterion("FILLDBL2 =", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2NotEqualTo(BigDecimal value) {
            addCriterion("FILLDBL2 <>", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2GreaterThan(BigDecimal value) {
            addCriterion("FILLDBL2 >", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL2 >=", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2LessThan(BigDecimal value) {
            addCriterion("FILLDBL2 <", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL2 <=", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2In(List<BigDecimal> values) {
            addCriterion("FILLDBL2 in", values, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2NotIn(List<BigDecimal> values) {
            addCriterion("FILLDBL2 not in", values, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL2 between", value1, value2, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL2 not between", value1, value2, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl22IsNull() {
            addCriterion("FILLDBL22 is null");
            return (Criteria) this;
        }

        public Criteria andFilldbl22IsNotNull() {
            addCriterion("FILLDBL22 is not null");
            return (Criteria) this;
        }

        public Criteria andFilldbl22EqualTo(BigDecimal value) {
            addCriterion("FILLDBL22 =", value, "filldbl22");
            return (Criteria) this;
        }

        public Criteria andFilldbl22NotEqualTo(BigDecimal value) {
            addCriterion("FILLDBL22 <>", value, "filldbl22");
            return (Criteria) this;
        }

        public Criteria andFilldbl22GreaterThan(BigDecimal value) {
            addCriterion("FILLDBL22 >", value, "filldbl22");
            return (Criteria) this;
        }

        public Criteria andFilldbl22GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL22 >=", value, "filldbl22");
            return (Criteria) this;
        }

        public Criteria andFilldbl22LessThan(BigDecimal value) {
            addCriterion("FILLDBL22 <", value, "filldbl22");
            return (Criteria) this;
        }

        public Criteria andFilldbl22LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL22 <=", value, "filldbl22");
            return (Criteria) this;
        }

        public Criteria andFilldbl22In(List<BigDecimal> values) {
            addCriterion("FILLDBL22 in", values, "filldbl22");
            return (Criteria) this;
        }

        public Criteria andFilldbl22NotIn(List<BigDecimal> values) {
            addCriterion("FILLDBL22 not in", values, "filldbl22");
            return (Criteria) this;
        }

        public Criteria andFilldbl22Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL22 between", value1, value2, "filldbl22");
            return (Criteria) this;
        }

        public Criteria andFilldbl22NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL22 not between", value1, value2, "filldbl22");
            return (Criteria) this;
        }

        public Criteria andFilldbl4IsNull() {
            addCriterion("FILLDBL4 is null");
            return (Criteria) this;
        }

        public Criteria andFilldbl4IsNotNull() {
            addCriterion("FILLDBL4 is not null");
            return (Criteria) this;
        }

        public Criteria andFilldbl4EqualTo(BigDecimal value) {
            addCriterion("FILLDBL4 =", value, "filldbl4");
            return (Criteria) this;
        }

        public Criteria andFilldbl4NotEqualTo(BigDecimal value) {
            addCriterion("FILLDBL4 <>", value, "filldbl4");
            return (Criteria) this;
        }

        public Criteria andFilldbl4GreaterThan(BigDecimal value) {
            addCriterion("FILLDBL4 >", value, "filldbl4");
            return (Criteria) this;
        }

        public Criteria andFilldbl4GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL4 >=", value, "filldbl4");
            return (Criteria) this;
        }

        public Criteria andFilldbl4LessThan(BigDecimal value) {
            addCriterion("FILLDBL4 <", value, "filldbl4");
            return (Criteria) this;
        }

        public Criteria andFilldbl4LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL4 <=", value, "filldbl4");
            return (Criteria) this;
        }

        public Criteria andFilldbl4In(List<BigDecimal> values) {
            addCriterion("FILLDBL4 in", values, "filldbl4");
            return (Criteria) this;
        }

        public Criteria andFilldbl4NotIn(List<BigDecimal> values) {
            addCriterion("FILLDBL4 not in", values, "filldbl4");
            return (Criteria) this;
        }

        public Criteria andFilldbl4Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL4 between", value1, value2, "filldbl4");
            return (Criteria) this;
        }

        public Criteria andFilldbl4NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL4 not between", value1, value2, "filldbl4");
            return (Criteria) this;
        }

        public Criteria andFilldate1IsNull() {
            addCriterion("FILLDATE1 is null");
            return (Criteria) this;
        }

        public Criteria andFilldate1IsNotNull() {
            addCriterion("FILLDATE1 is not null");
            return (Criteria) this;
        }

        public Criteria andFilldate1EqualTo(Date value) {
            addCriterion("FILLDATE1 =", value, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1NotEqualTo(Date value) {
            addCriterion("FILLDATE1 <>", value, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1GreaterThan(Date value) {
            addCriterion("FILLDATE1 >", value, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1GreaterThanOrEqualTo(Date value) {
            addCriterion("FILLDATE1 >=", value, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1LessThan(Date value) {
            addCriterion("FILLDATE1 <", value, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1LessThanOrEqualTo(Date value) {
            addCriterion("FILLDATE1 <=", value, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1In(List<Date> values) {
            addCriterion("FILLDATE1 in", values, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1NotIn(List<Date> values) {
            addCriterion("FILLDATE1 not in", values, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1Between(Date value1, Date value2) {
            addCriterion("FILLDATE1 between", value1, value2, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1NotBetween(Date value1, Date value2) {
            addCriterion("FILLDATE1 not between", value1, value2, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate2IsNull() {
            addCriterion("FILLDATE2 is null");
            return (Criteria) this;
        }

        public Criteria andFilldate2IsNotNull() {
            addCriterion("FILLDATE2 is not null");
            return (Criteria) this;
        }

        public Criteria andFilldate2EqualTo(Date value) {
            addCriterion("FILLDATE2 =", value, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2NotEqualTo(Date value) {
            addCriterion("FILLDATE2 <>", value, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2GreaterThan(Date value) {
            addCriterion("FILLDATE2 >", value, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2GreaterThanOrEqualTo(Date value) {
            addCriterion("FILLDATE2 >=", value, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2LessThan(Date value) {
            addCriterion("FILLDATE2 <", value, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2LessThanOrEqualTo(Date value) {
            addCriterion("FILLDATE2 <=", value, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2In(List<Date> values) {
            addCriterion("FILLDATE2 in", values, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2NotIn(List<Date> values) {
            addCriterion("FILLDATE2 not in", values, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2Between(Date value1, Date value2) {
            addCriterion("FILLDATE2 between", value1, value2, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2NotBetween(Date value1, Date value2) {
            addCriterion("FILLDATE2 not between", value1, value2, "filldate2");
            return (Criteria) this;
        }

        public Criteria andDqdmIsNull() {
            addCriterion("DQDM is null");
            return (Criteria) this;
        }

        public Criteria andDqdmIsNotNull() {
            addCriterion("DQDM is not null");
            return (Criteria) this;
        }

        public Criteria andDqdmEqualTo(String value) {
            addCriterion("DQDM =", value, "dqdm");
            return (Criteria) this;
        }

        public Criteria andDqdmNotEqualTo(String value) {
            addCriterion("DQDM <>", value, "dqdm");
            return (Criteria) this;
        }

        public Criteria andDqdmGreaterThan(String value) {
            addCriterion("DQDM >", value, "dqdm");
            return (Criteria) this;
        }

        public Criteria andDqdmGreaterThanOrEqualTo(String value) {
            addCriterion("DQDM >=", value, "dqdm");
            return (Criteria) this;
        }

        public Criteria andDqdmLessThan(String value) {
            addCriterion("DQDM <", value, "dqdm");
            return (Criteria) this;
        }

        public Criteria andDqdmLessThanOrEqualTo(String value) {
            addCriterion("DQDM <=", value, "dqdm");
            return (Criteria) this;
        }

        public Criteria andDqdmLike(String value) {
            addCriterion("DQDM like", value, "dqdm");
            return (Criteria) this;
        }

        public Criteria andDqdmNotLike(String value) {
            addCriterion("DQDM not like", value, "dqdm");
            return (Criteria) this;
        }

        public Criteria andDqdmIn(List<String> values) {
            addCriterion("DQDM in", values, "dqdm");
            return (Criteria) this;
        }

        public Criteria andDqdmNotIn(List<String> values) {
            addCriterion("DQDM not in", values, "dqdm");
            return (Criteria) this;
        }

        public Criteria andDqdmBetween(String value1, String value2) {
            addCriterion("DQDM between", value1, value2, "dqdm");
            return (Criteria) this;
        }

        public Criteria andDqdmNotBetween(String value1, String value2) {
            addCriterion("DQDM not between", value1, value2, "dqdm");
            return (Criteria) this;
        }

        public Criteria andMkdmIsNull() {
            addCriterion("MKDM is null");
            return (Criteria) this;
        }

        public Criteria andMkdmIsNotNull() {
            addCriterion("MKDM is not null");
            return (Criteria) this;
        }

        public Criteria andMkdmEqualTo(String value) {
            addCriterion("MKDM =", value, "mkdm");
            return (Criteria) this;
        }

        public Criteria andMkdmNotEqualTo(String value) {
            addCriterion("MKDM <>", value, "mkdm");
            return (Criteria) this;
        }

        public Criteria andMkdmGreaterThan(String value) {
            addCriterion("MKDM >", value, "mkdm");
            return (Criteria) this;
        }

        public Criteria andMkdmGreaterThanOrEqualTo(String value) {
            addCriterion("MKDM >=", value, "mkdm");
            return (Criteria) this;
        }

        public Criteria andMkdmLessThan(String value) {
            addCriterion("MKDM <", value, "mkdm");
            return (Criteria) this;
        }

        public Criteria andMkdmLessThanOrEqualTo(String value) {
            addCriterion("MKDM <=", value, "mkdm");
            return (Criteria) this;
        }

        public Criteria andMkdmLike(String value) {
            addCriterion("MKDM like", value, "mkdm");
            return (Criteria) this;
        }

        public Criteria andMkdmNotLike(String value) {
            addCriterion("MKDM not like", value, "mkdm");
            return (Criteria) this;
        }

        public Criteria andMkdmIn(List<String> values) {
            addCriterion("MKDM in", values, "mkdm");
            return (Criteria) this;
        }

        public Criteria andMkdmNotIn(List<String> values) {
            addCriterion("MKDM not in", values, "mkdm");
            return (Criteria) this;
        }

        public Criteria andMkdmBetween(String value1, String value2) {
            addCriterion("MKDM between", value1, value2, "mkdm");
            return (Criteria) this;
        }

        public Criteria andMkdmNotBetween(String value1, String value2) {
            addCriterion("MKDM not between", value1, value2, "mkdm");
            return (Criteria) this;
        }

        public Criteria andDeptindexIsNull() {
            addCriterion("DEPTINDEX is null");
            return (Criteria) this;
        }

        public Criteria andDeptindexIsNotNull() {
            addCriterion("DEPTINDEX is not null");
            return (Criteria) this;
        }

        public Criteria andDeptindexEqualTo(Short value) {
            addCriterion("DEPTINDEX =", value, "deptindex");
            return (Criteria) this;
        }

        public Criteria andDeptindexNotEqualTo(Short value) {
            addCriterion("DEPTINDEX <>", value, "deptindex");
            return (Criteria) this;
        }

        public Criteria andDeptindexGreaterThan(Short value) {
            addCriterion("DEPTINDEX >", value, "deptindex");
            return (Criteria) this;
        }

        public Criteria andDeptindexGreaterThanOrEqualTo(Short value) {
            addCriterion("DEPTINDEX >=", value, "deptindex");
            return (Criteria) this;
        }

        public Criteria andDeptindexLessThan(Short value) {
            addCriterion("DEPTINDEX <", value, "deptindex");
            return (Criteria) this;
        }

        public Criteria andDeptindexLessThanOrEqualTo(Short value) {
            addCriterion("DEPTINDEX <=", value, "deptindex");
            return (Criteria) this;
        }

        public Criteria andDeptindexIn(List<Short> values) {
            addCriterion("DEPTINDEX in", values, "deptindex");
            return (Criteria) this;
        }

        public Criteria andDeptindexNotIn(List<Short> values) {
            addCriterion("DEPTINDEX not in", values, "deptindex");
            return (Criteria) this;
        }

        public Criteria andDeptindexBetween(Short value1, Short value2) {
            addCriterion("DEPTINDEX between", value1, value2, "deptindex");
            return (Criteria) this;
        }

        public Criteria andDeptindexNotBetween(Short value1, Short value2) {
            addCriterion("DEPTINDEX not between", value1, value2, "deptindex");
            return (Criteria) this;
        }

        public Criteria andDeptguidIsNull() {
            addCriterion("DEPTGUID is null");
            return (Criteria) this;
        }

        public Criteria andDeptguidIsNotNull() {
            addCriterion("DEPTGUID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptguidEqualTo(String value) {
            addCriterion("DEPTGUID =", value, "deptguid");
            return (Criteria) this;
        }

        public Criteria andDeptguidNotEqualTo(String value) {
            addCriterion("DEPTGUID <>", value, "deptguid");
            return (Criteria) this;
        }

        public Criteria andDeptguidGreaterThan(String value) {
            addCriterion("DEPTGUID >", value, "deptguid");
            return (Criteria) this;
        }

        public Criteria andDeptguidGreaterThanOrEqualTo(String value) {
            addCriterion("DEPTGUID >=", value, "deptguid");
            return (Criteria) this;
        }

        public Criteria andDeptguidLessThan(String value) {
            addCriterion("DEPTGUID <", value, "deptguid");
            return (Criteria) this;
        }

        public Criteria andDeptguidLessThanOrEqualTo(String value) {
            addCriterion("DEPTGUID <=", value, "deptguid");
            return (Criteria) this;
        }

        public Criteria andDeptguidLike(String value) {
            addCriterion("DEPTGUID like", value, "deptguid");
            return (Criteria) this;
        }

        public Criteria andDeptguidNotLike(String value) {
            addCriterion("DEPTGUID not like", value, "deptguid");
            return (Criteria) this;
        }

        public Criteria andDeptguidIn(List<String> values) {
            addCriterion("DEPTGUID in", values, "deptguid");
            return (Criteria) this;
        }

        public Criteria andDeptguidNotIn(List<String> values) {
            addCriterion("DEPTGUID not in", values, "deptguid");
            return (Criteria) this;
        }

        public Criteria andDeptguidBetween(String value1, String value2) {
            addCriterion("DEPTGUID between", value1, value2, "deptguid");
            return (Criteria) this;
        }

        public Criteria andDeptguidNotBetween(String value1, String value2) {
            addCriterion("DEPTGUID not between", value1, value2, "deptguid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PTDEPT
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 23 18:13:28 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PTDEPT
     *
     * @mbggenerated Tue Jun 23 18:13:28 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}