package skyline.platform.repository.model;

public class Ptenumain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTENUMAIN.ENUTYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String enutype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTENUMAIN.ENUNAME
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String enuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTENUMAIN.VALUETYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String valuetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTENUMAIN.ENUDESC
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String enudesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTENUMAIN.ENUTYPE
     *
     * @return the value of PTENUMAIN.ENUTYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getEnutype() {
        return enutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTENUMAIN.ENUTYPE
     *
     * @param enutype the value for PTENUMAIN.ENUTYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setEnutype(String enutype) {
        this.enutype = enutype == null ? null : enutype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTENUMAIN.ENUNAME
     *
     * @return the value of PTENUMAIN.ENUNAME
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getEnuname() {
        return enuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTENUMAIN.ENUNAME
     *
     * @param enuname the value for PTENUMAIN.ENUNAME
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setEnuname(String enuname) {
        this.enuname = enuname == null ? null : enuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTENUMAIN.VALUETYPE
     *
     * @return the value of PTENUMAIN.VALUETYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getValuetype() {
        return valuetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTENUMAIN.VALUETYPE
     *
     * @param valuetype the value for PTENUMAIN.VALUETYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setValuetype(String valuetype) {
        this.valuetype = valuetype == null ? null : valuetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTENUMAIN.ENUDESC
     *
     * @return the value of PTENUMAIN.ENUDESC
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getEnudesc() {
        return enudesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTENUMAIN.ENUDESC
     *
     * @param enudesc the value for PTENUMAIN.ENUDESC
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setEnudesc(String enudesc) {
        this.enudesc = enudesc == null ? null : enudesc.trim();
    }
}