package skyline.platform.repository.model;

public class Pterror {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTERROR.MOUDLEID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String moudleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTERROR.ERRORTYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String errortype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTERROR.ERRORINDEX
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String errorindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTERROR.MESSAGE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTERROR.FILL1
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String fill1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTERROR.MOUDLEID
     *
     * @return the value of PTERROR.MOUDLEID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getMoudleid() {
        return moudleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTERROR.MOUDLEID
     *
     * @param moudleid the value for PTERROR.MOUDLEID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setMoudleid(String moudleid) {
        this.moudleid = moudleid == null ? null : moudleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTERROR.ERRORTYPE
     *
     * @return the value of PTERROR.ERRORTYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getErrortype() {
        return errortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTERROR.ERRORTYPE
     *
     * @param errortype the value for PTERROR.ERRORTYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setErrortype(String errortype) {
        this.errortype = errortype == null ? null : errortype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTERROR.ERRORINDEX
     *
     * @return the value of PTERROR.ERRORINDEX
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getErrorindex() {
        return errorindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTERROR.ERRORINDEX
     *
     * @param errorindex the value for PTERROR.ERRORINDEX
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setErrorindex(String errorindex) {
        this.errorindex = errorindex == null ? null : errorindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTERROR.MESSAGE
     *
     * @return the value of PTERROR.MESSAGE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTERROR.MESSAGE
     *
     * @param message the value for PTERROR.MESSAGE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTERROR.FILL1
     *
     * @return the value of PTERROR.FILL1
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getFill1() {
        return fill1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTERROR.FILL1
     *
     * @param fill1 the value for PTERROR.FILL1
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFill1(String fill1) {
        this.fill1 = fill1 == null ? null : fill1.trim();
    }
}