package skyline.platform.repository.model;

public class Ptlogicact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTLOGICACT.LOGICCODE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String logiccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTLOGICACT.LOGICCLASS
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String logicclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTLOGICACT.LOGICMETHOD
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String logicmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTLOGICACT.LOGICDESC
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String logicdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTLOGICACT.LOGICENABLED
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String logicenabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTLOGICACT.LOGICCODE
     *
     * @return the value of PTLOGICACT.LOGICCODE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getLogiccode() {
        return logiccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTLOGICACT.LOGICCODE
     *
     * @param logiccode the value for PTLOGICACT.LOGICCODE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setLogiccode(String logiccode) {
        this.logiccode = logiccode == null ? null : logiccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTLOGICACT.LOGICCLASS
     *
     * @return the value of PTLOGICACT.LOGICCLASS
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getLogicclass() {
        return logicclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTLOGICACT.LOGICCLASS
     *
     * @param logicclass the value for PTLOGICACT.LOGICCLASS
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setLogicclass(String logicclass) {
        this.logicclass = logicclass == null ? null : logicclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTLOGICACT.LOGICMETHOD
     *
     * @return the value of PTLOGICACT.LOGICMETHOD
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getLogicmethod() {
        return logicmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTLOGICACT.LOGICMETHOD
     *
     * @param logicmethod the value for PTLOGICACT.LOGICMETHOD
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setLogicmethod(String logicmethod) {
        this.logicmethod = logicmethod == null ? null : logicmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTLOGICACT.LOGICDESC
     *
     * @return the value of PTLOGICACT.LOGICDESC
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getLogicdesc() {
        return logicdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTLOGICACT.LOGICDESC
     *
     * @param logicdesc the value for PTLOGICACT.LOGICDESC
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setLogicdesc(String logicdesc) {
        this.logicdesc = logicdesc == null ? null : logicdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTLOGICACT.LOGICENABLED
     *
     * @return the value of PTLOGICACT.LOGICENABLED
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getLogicenabled() {
        return logicenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTLOGICACT.LOGICENABLED
     *
     * @param logicenabled the value for PTLOGICACT.LOGICENABLED
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setLogicenabled(String logicenabled) {
        this.logicenabled = logicenabled == null ? null : logicenabled.trim();
    }
}