package skyline.platform.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PtmenuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public PtmenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMenuidIsNull() {
            addCriterion("MENUID is null");
            return (Criteria) this;
        }

        public Criteria andMenuidIsNotNull() {
            addCriterion("MENUID is not null");
            return (Criteria) this;
        }

        public Criteria andMenuidEqualTo(String value) {
            addCriterion("MENUID =", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotEqualTo(String value) {
            addCriterion("MENUID <>", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidGreaterThan(String value) {
            addCriterion("MENUID >", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidGreaterThanOrEqualTo(String value) {
            addCriterion("MENUID >=", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLessThan(String value) {
            addCriterion("MENUID <", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLessThanOrEqualTo(String value) {
            addCriterion("MENUID <=", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLike(String value) {
            addCriterion("MENUID like", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotLike(String value) {
            addCriterion("MENUID not like", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidIn(List<String> values) {
            addCriterion("MENUID in", values, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotIn(List<String> values) {
            addCriterion("MENUID not in", values, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidBetween(String value1, String value2) {
            addCriterion("MENUID between", value1, value2, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotBetween(String value1, String value2) {
            addCriterion("MENUID not between", value1, value2, "menuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidIsNull() {
            addCriterion("PARENTMENUID is null");
            return (Criteria) this;
        }

        public Criteria andParentmenuidIsNotNull() {
            addCriterion("PARENTMENUID is not null");
            return (Criteria) this;
        }

        public Criteria andParentmenuidEqualTo(String value) {
            addCriterion("PARENTMENUID =", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidNotEqualTo(String value) {
            addCriterion("PARENTMENUID <>", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidGreaterThan(String value) {
            addCriterion("PARENTMENUID >", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidGreaterThanOrEqualTo(String value) {
            addCriterion("PARENTMENUID >=", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidLessThan(String value) {
            addCriterion("PARENTMENUID <", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidLessThanOrEqualTo(String value) {
            addCriterion("PARENTMENUID <=", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidLike(String value) {
            addCriterion("PARENTMENUID like", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidNotLike(String value) {
            addCriterion("PARENTMENUID not like", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidIn(List<String> values) {
            addCriterion("PARENTMENUID in", values, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidNotIn(List<String> values) {
            addCriterion("PARENTMENUID not in", values, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidBetween(String value1, String value2) {
            addCriterion("PARENTMENUID between", value1, value2, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidNotBetween(String value1, String value2) {
            addCriterion("PARENTMENUID not between", value1, value2, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andMenulevelIsNull() {
            addCriterion("MENULEVEL is null");
            return (Criteria) this;
        }

        public Criteria andMenulevelIsNotNull() {
            addCriterion("MENULEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andMenulevelEqualTo(Short value) {
            addCriterion("MENULEVEL =", value, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelNotEqualTo(Short value) {
            addCriterion("MENULEVEL <>", value, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelGreaterThan(Short value) {
            addCriterion("MENULEVEL >", value, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelGreaterThanOrEqualTo(Short value) {
            addCriterion("MENULEVEL >=", value, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelLessThan(Short value) {
            addCriterion("MENULEVEL <", value, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelLessThanOrEqualTo(Short value) {
            addCriterion("MENULEVEL <=", value, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelIn(List<Short> values) {
            addCriterion("MENULEVEL in", values, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelNotIn(List<Short> values) {
            addCriterion("MENULEVEL not in", values, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelBetween(Short value1, Short value2) {
            addCriterion("MENULEVEL between", value1, value2, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelNotBetween(Short value1, Short value2) {
            addCriterion("MENULEVEL not between", value1, value2, "menulevel");
            return (Criteria) this;
        }

        public Criteria andIsleafIsNull() {
            addCriterion("ISLEAF is null");
            return (Criteria) this;
        }

        public Criteria andIsleafIsNotNull() {
            addCriterion("ISLEAF is not null");
            return (Criteria) this;
        }

        public Criteria andIsleafEqualTo(Short value) {
            addCriterion("ISLEAF =", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotEqualTo(Short value) {
            addCriterion("ISLEAF <>", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafGreaterThan(Short value) {
            addCriterion("ISLEAF >", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafGreaterThanOrEqualTo(Short value) {
            addCriterion("ISLEAF >=", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafLessThan(Short value) {
            addCriterion("ISLEAF <", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafLessThanOrEqualTo(Short value) {
            addCriterion("ISLEAF <=", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafIn(List<Short> values) {
            addCriterion("ISLEAF in", values, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotIn(List<Short> values) {
            addCriterion("ISLEAF not in", values, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafBetween(Short value1, Short value2) {
            addCriterion("ISLEAF between", value1, value2, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotBetween(Short value1, Short value2) {
            addCriterion("ISLEAF not between", value1, value2, "isleaf");
            return (Criteria) this;
        }

        public Criteria andMenudescIsNull() {
            addCriterion("MENUDESC is null");
            return (Criteria) this;
        }

        public Criteria andMenudescIsNotNull() {
            addCriterion("MENUDESC is not null");
            return (Criteria) this;
        }

        public Criteria andMenudescEqualTo(String value) {
            addCriterion("MENUDESC =", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescNotEqualTo(String value) {
            addCriterion("MENUDESC <>", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescGreaterThan(String value) {
            addCriterion("MENUDESC >", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescGreaterThanOrEqualTo(String value) {
            addCriterion("MENUDESC >=", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescLessThan(String value) {
            addCriterion("MENUDESC <", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescLessThanOrEqualTo(String value) {
            addCriterion("MENUDESC <=", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescLike(String value) {
            addCriterion("MENUDESC like", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescNotLike(String value) {
            addCriterion("MENUDESC not like", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescIn(List<String> values) {
            addCriterion("MENUDESC in", values, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescNotIn(List<String> values) {
            addCriterion("MENUDESC not in", values, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescBetween(String value1, String value2) {
            addCriterion("MENUDESC between", value1, value2, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescNotBetween(String value1, String value2) {
            addCriterion("MENUDESC not between", value1, value2, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenulabelIsNull() {
            addCriterion("MENULABEL is null");
            return (Criteria) this;
        }

        public Criteria andMenulabelIsNotNull() {
            addCriterion("MENULABEL is not null");
            return (Criteria) this;
        }

        public Criteria andMenulabelEqualTo(String value) {
            addCriterion("MENULABEL =", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelNotEqualTo(String value) {
            addCriterion("MENULABEL <>", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelGreaterThan(String value) {
            addCriterion("MENULABEL >", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelGreaterThanOrEqualTo(String value) {
            addCriterion("MENULABEL >=", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelLessThan(String value) {
            addCriterion("MENULABEL <", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelLessThanOrEqualTo(String value) {
            addCriterion("MENULABEL <=", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelLike(String value) {
            addCriterion("MENULABEL like", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelNotLike(String value) {
            addCriterion("MENULABEL not like", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelIn(List<String> values) {
            addCriterion("MENULABEL in", values, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelNotIn(List<String> values) {
            addCriterion("MENULABEL not in", values, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelBetween(String value1, String value2) {
            addCriterion("MENULABEL between", value1, value2, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelNotBetween(String value1, String value2) {
            addCriterion("MENULABEL not between", value1, value2, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenuiconIsNull() {
            addCriterion("MENUICON is null");
            return (Criteria) this;
        }

        public Criteria andMenuiconIsNotNull() {
            addCriterion("MENUICON is not null");
            return (Criteria) this;
        }

        public Criteria andMenuiconEqualTo(String value) {
            addCriterion("MENUICON =", value, "menuicon");
            return (Criteria) this;
        }

        public Criteria andMenuiconNotEqualTo(String value) {
            addCriterion("MENUICON <>", value, "menuicon");
            return (Criteria) this;
        }

        public Criteria andMenuiconGreaterThan(String value) {
            addCriterion("MENUICON >", value, "menuicon");
            return (Criteria) this;
        }

        public Criteria andMenuiconGreaterThanOrEqualTo(String value) {
            addCriterion("MENUICON >=", value, "menuicon");
            return (Criteria) this;
        }

        public Criteria andMenuiconLessThan(String value) {
            addCriterion("MENUICON <", value, "menuicon");
            return (Criteria) this;
        }

        public Criteria andMenuiconLessThanOrEqualTo(String value) {
            addCriterion("MENUICON <=", value, "menuicon");
            return (Criteria) this;
        }

        public Criteria andMenuiconLike(String value) {
            addCriterion("MENUICON like", value, "menuicon");
            return (Criteria) this;
        }

        public Criteria andMenuiconNotLike(String value) {
            addCriterion("MENUICON not like", value, "menuicon");
            return (Criteria) this;
        }

        public Criteria andMenuiconIn(List<String> values) {
            addCriterion("MENUICON in", values, "menuicon");
            return (Criteria) this;
        }

        public Criteria andMenuiconNotIn(List<String> values) {
            addCriterion("MENUICON not in", values, "menuicon");
            return (Criteria) this;
        }

        public Criteria andMenuiconBetween(String value1, String value2) {
            addCriterion("MENUICON between", value1, value2, "menuicon");
            return (Criteria) this;
        }

        public Criteria andMenuiconNotBetween(String value1, String value2) {
            addCriterion("MENUICON not between", value1, value2, "menuicon");
            return (Criteria) this;
        }

        public Criteria andOpeniconIsNull() {
            addCriterion("OPENICON is null");
            return (Criteria) this;
        }

        public Criteria andOpeniconIsNotNull() {
            addCriterion("OPENICON is not null");
            return (Criteria) this;
        }

        public Criteria andOpeniconEqualTo(String value) {
            addCriterion("OPENICON =", value, "openicon");
            return (Criteria) this;
        }

        public Criteria andOpeniconNotEqualTo(String value) {
            addCriterion("OPENICON <>", value, "openicon");
            return (Criteria) this;
        }

        public Criteria andOpeniconGreaterThan(String value) {
            addCriterion("OPENICON >", value, "openicon");
            return (Criteria) this;
        }

        public Criteria andOpeniconGreaterThanOrEqualTo(String value) {
            addCriterion("OPENICON >=", value, "openicon");
            return (Criteria) this;
        }

        public Criteria andOpeniconLessThan(String value) {
            addCriterion("OPENICON <", value, "openicon");
            return (Criteria) this;
        }

        public Criteria andOpeniconLessThanOrEqualTo(String value) {
            addCriterion("OPENICON <=", value, "openicon");
            return (Criteria) this;
        }

        public Criteria andOpeniconLike(String value) {
            addCriterion("OPENICON like", value, "openicon");
            return (Criteria) this;
        }

        public Criteria andOpeniconNotLike(String value) {
            addCriterion("OPENICON not like", value, "openicon");
            return (Criteria) this;
        }

        public Criteria andOpeniconIn(List<String> values) {
            addCriterion("OPENICON in", values, "openicon");
            return (Criteria) this;
        }

        public Criteria andOpeniconNotIn(List<String> values) {
            addCriterion("OPENICON not in", values, "openicon");
            return (Criteria) this;
        }

        public Criteria andOpeniconBetween(String value1, String value2) {
            addCriterion("OPENICON between", value1, value2, "openicon");
            return (Criteria) this;
        }

        public Criteria andOpeniconNotBetween(String value1, String value2) {
            addCriterion("OPENICON not between", value1, value2, "openicon");
            return (Criteria) this;
        }

        public Criteria andTargetmachineIsNull() {
            addCriterion("TARGETMACHINE is null");
            return (Criteria) this;
        }

        public Criteria andTargetmachineIsNotNull() {
            addCriterion("TARGETMACHINE is not null");
            return (Criteria) this;
        }

        public Criteria andTargetmachineEqualTo(String value) {
            addCriterion("TARGETMACHINE =", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineNotEqualTo(String value) {
            addCriterion("TARGETMACHINE <>", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineGreaterThan(String value) {
            addCriterion("TARGETMACHINE >", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineGreaterThanOrEqualTo(String value) {
            addCriterion("TARGETMACHINE >=", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineLessThan(String value) {
            addCriterion("TARGETMACHINE <", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineLessThanOrEqualTo(String value) {
            addCriterion("TARGETMACHINE <=", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineLike(String value) {
            addCriterion("TARGETMACHINE like", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineNotLike(String value) {
            addCriterion("TARGETMACHINE not like", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineIn(List<String> values) {
            addCriterion("TARGETMACHINE in", values, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineNotIn(List<String> values) {
            addCriterion("TARGETMACHINE not in", values, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineBetween(String value1, String value2) {
            addCriterion("TARGETMACHINE between", value1, value2, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineNotBetween(String value1, String value2) {
            addCriterion("TARGETMACHINE not between", value1, value2, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andMenuactionIsNull() {
            addCriterion("MENUACTION is null");
            return (Criteria) this;
        }

        public Criteria andMenuactionIsNotNull() {
            addCriterion("MENUACTION is not null");
            return (Criteria) this;
        }

        public Criteria andMenuactionEqualTo(String value) {
            addCriterion("MENUACTION =", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionNotEqualTo(String value) {
            addCriterion("MENUACTION <>", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionGreaterThan(String value) {
            addCriterion("MENUACTION >", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionGreaterThanOrEqualTo(String value) {
            addCriterion("MENUACTION >=", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionLessThan(String value) {
            addCriterion("MENUACTION <", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionLessThanOrEqualTo(String value) {
            addCriterion("MENUACTION <=", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionLike(String value) {
            addCriterion("MENUACTION like", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionNotLike(String value) {
            addCriterion("MENUACTION not like", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionIn(List<String> values) {
            addCriterion("MENUACTION in", values, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionNotIn(List<String> values) {
            addCriterion("MENUACTION not in", values, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionBetween(String value1, String value2) {
            addCriterion("MENUACTION between", value1, value2, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionNotBetween(String value1, String value2) {
            addCriterion("MENUACTION not between", value1, value2, "menuaction");
            return (Criteria) this;
        }

        public Criteria andOpenwindowIsNull() {
            addCriterion("OPENWINDOW is null");
            return (Criteria) this;
        }

        public Criteria andOpenwindowIsNotNull() {
            addCriterion("OPENWINDOW is not null");
            return (Criteria) this;
        }

        public Criteria andOpenwindowEqualTo(String value) {
            addCriterion("OPENWINDOW =", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowNotEqualTo(String value) {
            addCriterion("OPENWINDOW <>", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowGreaterThan(String value) {
            addCriterion("OPENWINDOW >", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowGreaterThanOrEqualTo(String value) {
            addCriterion("OPENWINDOW >=", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowLessThan(String value) {
            addCriterion("OPENWINDOW <", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowLessThanOrEqualTo(String value) {
            addCriterion("OPENWINDOW <=", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowLike(String value) {
            addCriterion("OPENWINDOW like", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowNotLike(String value) {
            addCriterion("OPENWINDOW not like", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowIn(List<String> values) {
            addCriterion("OPENWINDOW in", values, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowNotIn(List<String> values) {
            addCriterion("OPENWINDOW not in", values, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowBetween(String value1, String value2) {
            addCriterion("OPENWINDOW between", value1, value2, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowNotBetween(String value1, String value2) {
            addCriterion("OPENWINDOW not between", value1, value2, "openwindow");
            return (Criteria) this;
        }

        public Criteria andWindowwidthIsNull() {
            addCriterion("WINDOWWIDTH is null");
            return (Criteria) this;
        }

        public Criteria andWindowwidthIsNotNull() {
            addCriterion("WINDOWWIDTH is not null");
            return (Criteria) this;
        }

        public Criteria andWindowwidthEqualTo(Short value) {
            addCriterion("WINDOWWIDTH =", value, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthNotEqualTo(Short value) {
            addCriterion("WINDOWWIDTH <>", value, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthGreaterThan(Short value) {
            addCriterion("WINDOWWIDTH >", value, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthGreaterThanOrEqualTo(Short value) {
            addCriterion("WINDOWWIDTH >=", value, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthLessThan(Short value) {
            addCriterion("WINDOWWIDTH <", value, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthLessThanOrEqualTo(Short value) {
            addCriterion("WINDOWWIDTH <=", value, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthIn(List<Short> values) {
            addCriterion("WINDOWWIDTH in", values, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthNotIn(List<Short> values) {
            addCriterion("WINDOWWIDTH not in", values, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthBetween(Short value1, Short value2) {
            addCriterion("WINDOWWIDTH between", value1, value2, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthNotBetween(Short value1, Short value2) {
            addCriterion("WINDOWWIDTH not between", value1, value2, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowheightIsNull() {
            addCriterion("WINDOWHEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andWindowheightIsNotNull() {
            addCriterion("WINDOWHEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andWindowheightEqualTo(Short value) {
            addCriterion("WINDOWHEIGHT =", value, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightNotEqualTo(Short value) {
            addCriterion("WINDOWHEIGHT <>", value, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightGreaterThan(Short value) {
            addCriterion("WINDOWHEIGHT >", value, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightGreaterThanOrEqualTo(Short value) {
            addCriterion("WINDOWHEIGHT >=", value, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightLessThan(Short value) {
            addCriterion("WINDOWHEIGHT <", value, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightLessThanOrEqualTo(Short value) {
            addCriterion("WINDOWHEIGHT <=", value, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightIn(List<Short> values) {
            addCriterion("WINDOWHEIGHT in", values, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightNotIn(List<Short> values) {
            addCriterion("WINDOWHEIGHT not in", values, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightBetween(Short value1, Short value2) {
            addCriterion("WINDOWHEIGHT between", value1, value2, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightNotBetween(Short value1, Short value2) {
            addCriterion("WINDOWHEIGHT not between", value1, value2, "windowheight");
            return (Criteria) this;
        }

        public Criteria andLevelidxIsNull() {
            addCriterion("LEVELIDX is null");
            return (Criteria) this;
        }

        public Criteria andLevelidxIsNotNull() {
            addCriterion("LEVELIDX is not null");
            return (Criteria) this;
        }

        public Criteria andLevelidxEqualTo(Integer value) {
            addCriterion("LEVELIDX =", value, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxNotEqualTo(Integer value) {
            addCriterion("LEVELIDX <>", value, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxGreaterThan(Integer value) {
            addCriterion("LEVELIDX >", value, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxGreaterThanOrEqualTo(Integer value) {
            addCriterion("LEVELIDX >=", value, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxLessThan(Integer value) {
            addCriterion("LEVELIDX <", value, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxLessThanOrEqualTo(Integer value) {
            addCriterion("LEVELIDX <=", value, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxIn(List<Integer> values) {
            addCriterion("LEVELIDX in", values, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxNotIn(List<Integer> values) {
            addCriterion("LEVELIDX not in", values, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxBetween(Integer value1, Integer value2) {
            addCriterion("LEVELIDX between", value1, value2, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxNotBetween(Integer value1, Integer value2) {
            addCriterion("LEVELIDX not between", value1, value2, "levelidx");
            return (Criteria) this;
        }

        public Criteria andFillstr50IsNull() {
            addCriterion("FILLSTR50 is null");
            return (Criteria) this;
        }

        public Criteria andFillstr50IsNotNull() {
            addCriterion("FILLSTR50 is not null");
            return (Criteria) this;
        }

        public Criteria andFillstr50EqualTo(String value) {
            addCriterion("FILLSTR50 =", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50NotEqualTo(String value) {
            addCriterion("FILLSTR50 <>", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50GreaterThan(String value) {
            addCriterion("FILLSTR50 >", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50GreaterThanOrEqualTo(String value) {
            addCriterion("FILLSTR50 >=", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50LessThan(String value) {
            addCriterion("FILLSTR50 <", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50LessThanOrEqualTo(String value) {
            addCriterion("FILLSTR50 <=", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50Like(String value) {
            addCriterion("FILLSTR50 like", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50NotLike(String value) {
            addCriterion("FILLSTR50 not like", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50In(List<String> values) {
            addCriterion("FILLSTR50 in", values, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50NotIn(List<String> values) {
            addCriterion("FILLSTR50 not in", values, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50Between(String value1, String value2) {
            addCriterion("FILLSTR50 between", value1, value2, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50NotBetween(String value1, String value2) {
            addCriterion("FILLSTR50 not between", value1, value2, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr100IsNull() {
            addCriterion("FILLSTR100 is null");
            return (Criteria) this;
        }

        public Criteria andFillstr100IsNotNull() {
            addCriterion("FILLSTR100 is not null");
            return (Criteria) this;
        }

        public Criteria andFillstr100EqualTo(String value) {
            addCriterion("FILLSTR100 =", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100NotEqualTo(String value) {
            addCriterion("FILLSTR100 <>", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100GreaterThan(String value) {
            addCriterion("FILLSTR100 >", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100GreaterThanOrEqualTo(String value) {
            addCriterion("FILLSTR100 >=", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100LessThan(String value) {
            addCriterion("FILLSTR100 <", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100LessThanOrEqualTo(String value) {
            addCriterion("FILLSTR100 <=", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100Like(String value) {
            addCriterion("FILLSTR100 like", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100NotLike(String value) {
            addCriterion("FILLSTR100 not like", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100In(List<String> values) {
            addCriterion("FILLSTR100 in", values, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100NotIn(List<String> values) {
            addCriterion("FILLSTR100 not in", values, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100Between(String value1, String value2) {
            addCriterion("FILLSTR100 between", value1, value2, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100NotBetween(String value1, String value2) {
            addCriterion("FILLSTR100 not between", value1, value2, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillint1IsNull() {
            addCriterion("FILLINT1 is null");
            return (Criteria) this;
        }

        public Criteria andFillint1IsNotNull() {
            addCriterion("FILLINT1 is not null");
            return (Criteria) this;
        }

        public Criteria andFillint1EqualTo(Long value) {
            addCriterion("FILLINT1 =", value, "fillint1");
            return (Criteria) this;
        }

        public Criteria andFillint1NotEqualTo(Long value) {
            addCriterion("FILLINT1 <>", value, "fillint1");
            return (Criteria) this;
        }

        public Criteria andFillint1GreaterThan(Long value) {
            addCriterion("FILLINT1 >", value, "fillint1");
            return (Criteria) this;
        }

        public Criteria andFillint1GreaterThanOrEqualTo(Long value) {
            addCriterion("FILLINT1 >=", value, "fillint1");
            return (Criteria) this;
        }

        public Criteria andFillint1LessThan(Long value) {
            addCriterion("FILLINT1 <", value, "fillint1");
            return (Criteria) this;
        }

        public Criteria andFillint1LessThanOrEqualTo(Long value) {
            addCriterion("FILLINT1 <=", value, "fillint1");
            return (Criteria) this;
        }

        public Criteria andFillint1In(List<Long> values) {
            addCriterion("FILLINT1 in", values, "fillint1");
            return (Criteria) this;
        }

        public Criteria andFillint1NotIn(List<Long> values) {
            addCriterion("FILLINT1 not in", values, "fillint1");
            return (Criteria) this;
        }

        public Criteria andFillint1Between(Long value1, Long value2) {
            addCriterion("FILLINT1 between", value1, value2, "fillint1");
            return (Criteria) this;
        }

        public Criteria andFillint1NotBetween(Long value1, Long value2) {
            addCriterion("FILLINT1 not between", value1, value2, "fillint1");
            return (Criteria) this;
        }

        public Criteria andFilldbl2IsNull() {
            addCriterion("FILLDBL2 is null");
            return (Criteria) this;
        }

        public Criteria andFilldbl2IsNotNull() {
            addCriterion("FILLDBL2 is not null");
            return (Criteria) this;
        }

        public Criteria andFilldbl2EqualTo(BigDecimal value) {
            addCriterion("FILLDBL2 =", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2NotEqualTo(BigDecimal value) {
            addCriterion("FILLDBL2 <>", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2GreaterThan(BigDecimal value) {
            addCriterion("FILLDBL2 >", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL2 >=", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2LessThan(BigDecimal value) {
            addCriterion("FILLDBL2 <", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL2 <=", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2In(List<BigDecimal> values) {
            addCriterion("FILLDBL2 in", values, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2NotIn(List<BigDecimal> values) {
            addCriterion("FILLDBL2 not in", values, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL2 between", value1, value2, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL2 not between", value1, value2, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldateIsNull() {
            addCriterion("FILLDATE is null");
            return (Criteria) this;
        }

        public Criteria andFilldateIsNotNull() {
            addCriterion("FILLDATE is not null");
            return (Criteria) this;
        }

        public Criteria andFilldateEqualTo(Date value) {
            addCriterion("FILLDATE =", value, "filldate");
            return (Criteria) this;
        }

        public Criteria andFilldateNotEqualTo(Date value) {
            addCriterion("FILLDATE <>", value, "filldate");
            return (Criteria) this;
        }

        public Criteria andFilldateGreaterThan(Date value) {
            addCriterion("FILLDATE >", value, "filldate");
            return (Criteria) this;
        }

        public Criteria andFilldateGreaterThanOrEqualTo(Date value) {
            addCriterion("FILLDATE >=", value, "filldate");
            return (Criteria) this;
        }

        public Criteria andFilldateLessThan(Date value) {
            addCriterion("FILLDATE <", value, "filldate");
            return (Criteria) this;
        }

        public Criteria andFilldateLessThanOrEqualTo(Date value) {
            addCriterion("FILLDATE <=", value, "filldate");
            return (Criteria) this;
        }

        public Criteria andFilldateIn(List<Date> values) {
            addCriterion("FILLDATE in", values, "filldate");
            return (Criteria) this;
        }

        public Criteria andFilldateNotIn(List<Date> values) {
            addCriterion("FILLDATE not in", values, "filldate");
            return (Criteria) this;
        }

        public Criteria andFilldateBetween(Date value1, Date value2) {
            addCriterion("FILLDATE between", value1, value2, "filldate");
            return (Criteria) this;
        }

        public Criteria andFilldateNotBetween(Date value1, Date value2) {
            addCriterion("FILLDATE not between", value1, value2, "filldate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PTMENU
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 23 18:13:29 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PTMENU
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}