package skyline.platform.repository.model;

import java.math.BigDecimal;
import java.util.Date;

public class Ptoper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.OPERID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.DEPTID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.OPERPASSWD
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String operpasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.ISSUPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String issuper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.OPERDUTY
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String operduty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.OPERTYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String opertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.OPERNAME
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String opername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.SEX
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.EMAIL
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.MOBILEPHONE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.OPERPHONE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String operphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.OTHERPHONE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String otherphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.OPERENABLED
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String operenabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLSTR50
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String fillstr50;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLSTR80
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String fillstr80;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLSTR100
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String fillstr100;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLSTR150
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String fillstr150;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLSTR600
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String fillstr600;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLDATE1
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private Date filldate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLDATE2
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private Date filldate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLDATE3
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private Date filldate3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLINT6
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private Integer fillint6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLINT8
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private Integer fillint8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLINT10
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private Long fillint10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLINT12
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private Long fillint12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLINTVAR
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private Short fillintvar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLDBL1
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private BigDecimal filldbl1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLDBL2
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private BigDecimal filldbl2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.FILLDBL3
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private BigDecimal filldbl3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTOPER.USERGUID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String userguid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.OPERID
     *
     * @return the value of PTOPER.OPERID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.OPERID
     *
     * @param operid the value for PTOPER.OPERID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.DEPTID
     *
     * @return the value of PTOPER.DEPTID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.DEPTID
     *
     * @param deptid the value for PTOPER.DEPTID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.OPERPASSWD
     *
     * @return the value of PTOPER.OPERPASSWD
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getOperpasswd() {
        return operpasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.OPERPASSWD
     *
     * @param operpasswd the value for PTOPER.OPERPASSWD
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setOperpasswd(String operpasswd) {
        this.operpasswd = operpasswd == null ? null : operpasswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.ISSUPER
     *
     * @return the value of PTOPER.ISSUPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getIssuper() {
        return issuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.ISSUPER
     *
     * @param issuper the value for PTOPER.ISSUPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setIssuper(String issuper) {
        this.issuper = issuper == null ? null : issuper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.OPERDUTY
     *
     * @return the value of PTOPER.OPERDUTY
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getOperduty() {
        return operduty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.OPERDUTY
     *
     * @param operduty the value for PTOPER.OPERDUTY
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setOperduty(String operduty) {
        this.operduty = operduty == null ? null : operduty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.OPERTYPE
     *
     * @return the value of PTOPER.OPERTYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getOpertype() {
        return opertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.OPERTYPE
     *
     * @param opertype the value for PTOPER.OPERTYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setOpertype(String opertype) {
        this.opertype = opertype == null ? null : opertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.OPERNAME
     *
     * @return the value of PTOPER.OPERNAME
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getOpername() {
        return opername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.OPERNAME
     *
     * @param opername the value for PTOPER.OPERNAME
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setOpername(String opername) {
        this.opername = opername == null ? null : opername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.SEX
     *
     * @return the value of PTOPER.SEX
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.SEX
     *
     * @param sex the value for PTOPER.SEX
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.EMAIL
     *
     * @return the value of PTOPER.EMAIL
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.EMAIL
     *
     * @param email the value for PTOPER.EMAIL
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.MOBILEPHONE
     *
     * @return the value of PTOPER.MOBILEPHONE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.MOBILEPHONE
     *
     * @param mobilephone the value for PTOPER.MOBILEPHONE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.OPERPHONE
     *
     * @return the value of PTOPER.OPERPHONE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getOperphone() {
        return operphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.OPERPHONE
     *
     * @param operphone the value for PTOPER.OPERPHONE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setOperphone(String operphone) {
        this.operphone = operphone == null ? null : operphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.OTHERPHONE
     *
     * @return the value of PTOPER.OTHERPHONE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getOtherphone() {
        return otherphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.OTHERPHONE
     *
     * @param otherphone the value for PTOPER.OTHERPHONE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setOtherphone(String otherphone) {
        this.otherphone = otherphone == null ? null : otherphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.OPERENABLED
     *
     * @return the value of PTOPER.OPERENABLED
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getOperenabled() {
        return operenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.OPERENABLED
     *
     * @param operenabled the value for PTOPER.OPERENABLED
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setOperenabled(String operenabled) {
        this.operenabled = operenabled == null ? null : operenabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLSTR50
     *
     * @return the value of PTOPER.FILLSTR50
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getFillstr50() {
        return fillstr50;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLSTR50
     *
     * @param fillstr50 the value for PTOPER.FILLSTR50
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFillstr50(String fillstr50) {
        this.fillstr50 = fillstr50 == null ? null : fillstr50.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLSTR80
     *
     * @return the value of PTOPER.FILLSTR80
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getFillstr80() {
        return fillstr80;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLSTR80
     *
     * @param fillstr80 the value for PTOPER.FILLSTR80
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFillstr80(String fillstr80) {
        this.fillstr80 = fillstr80 == null ? null : fillstr80.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLSTR100
     *
     * @return the value of PTOPER.FILLSTR100
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getFillstr100() {
        return fillstr100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLSTR100
     *
     * @param fillstr100 the value for PTOPER.FILLSTR100
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFillstr100(String fillstr100) {
        this.fillstr100 = fillstr100 == null ? null : fillstr100.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLSTR150
     *
     * @return the value of PTOPER.FILLSTR150
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getFillstr150() {
        return fillstr150;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLSTR150
     *
     * @param fillstr150 the value for PTOPER.FILLSTR150
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFillstr150(String fillstr150) {
        this.fillstr150 = fillstr150 == null ? null : fillstr150.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLSTR600
     *
     * @return the value of PTOPER.FILLSTR600
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getFillstr600() {
        return fillstr600;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLSTR600
     *
     * @param fillstr600 the value for PTOPER.FILLSTR600
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFillstr600(String fillstr600) {
        this.fillstr600 = fillstr600 == null ? null : fillstr600.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLDATE1
     *
     * @return the value of PTOPER.FILLDATE1
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public Date getFilldate1() {
        return filldate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLDATE1
     *
     * @param filldate1 the value for PTOPER.FILLDATE1
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFilldate1(Date filldate1) {
        this.filldate1 = filldate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLDATE2
     *
     * @return the value of PTOPER.FILLDATE2
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public Date getFilldate2() {
        return filldate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLDATE2
     *
     * @param filldate2 the value for PTOPER.FILLDATE2
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFilldate2(Date filldate2) {
        this.filldate2 = filldate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLDATE3
     *
     * @return the value of PTOPER.FILLDATE3
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public Date getFilldate3() {
        return filldate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLDATE3
     *
     * @param filldate3 the value for PTOPER.FILLDATE3
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFilldate3(Date filldate3) {
        this.filldate3 = filldate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLINT6
     *
     * @return the value of PTOPER.FILLINT6
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public Integer getFillint6() {
        return fillint6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLINT6
     *
     * @param fillint6 the value for PTOPER.FILLINT6
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFillint6(Integer fillint6) {
        this.fillint6 = fillint6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLINT8
     *
     * @return the value of PTOPER.FILLINT8
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public Integer getFillint8() {
        return fillint8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLINT8
     *
     * @param fillint8 the value for PTOPER.FILLINT8
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFillint8(Integer fillint8) {
        this.fillint8 = fillint8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLINT10
     *
     * @return the value of PTOPER.FILLINT10
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public Long getFillint10() {
        return fillint10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLINT10
     *
     * @param fillint10 the value for PTOPER.FILLINT10
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFillint10(Long fillint10) {
        this.fillint10 = fillint10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLINT12
     *
     * @return the value of PTOPER.FILLINT12
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public Long getFillint12() {
        return fillint12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLINT12
     *
     * @param fillint12 the value for PTOPER.FILLINT12
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFillint12(Long fillint12) {
        this.fillint12 = fillint12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLINTVAR
     *
     * @return the value of PTOPER.FILLINTVAR
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public Short getFillintvar() {
        return fillintvar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLINTVAR
     *
     * @param fillintvar the value for PTOPER.FILLINTVAR
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFillintvar(Short fillintvar) {
        this.fillintvar = fillintvar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLDBL1
     *
     * @return the value of PTOPER.FILLDBL1
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public BigDecimal getFilldbl1() {
        return filldbl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLDBL1
     *
     * @param filldbl1 the value for PTOPER.FILLDBL1
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFilldbl1(BigDecimal filldbl1) {
        this.filldbl1 = filldbl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLDBL2
     *
     * @return the value of PTOPER.FILLDBL2
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public BigDecimal getFilldbl2() {
        return filldbl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLDBL2
     *
     * @param filldbl2 the value for PTOPER.FILLDBL2
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFilldbl2(BigDecimal filldbl2) {
        this.filldbl2 = filldbl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.FILLDBL3
     *
     * @return the value of PTOPER.FILLDBL3
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public BigDecimal getFilldbl3() {
        return filldbl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.FILLDBL3
     *
     * @param filldbl3 the value for PTOPER.FILLDBL3
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setFilldbl3(BigDecimal filldbl3) {
        this.filldbl3 = filldbl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTOPER.USERGUID
     *
     * @return the value of PTOPER.USERGUID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getUserguid() {
        return userguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTOPER.USERGUID
     *
     * @param userguid the value for PTOPER.USERGUID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setUserguid(String userguid) {
        this.userguid = userguid == null ? null : userguid.trim();
    }
}