package skyline.platform.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PtoperExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public PtoperExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOperidIsNull() {
            addCriterion("OPERID is null");
            return (Criteria) this;
        }

        public Criteria andOperidIsNotNull() {
            addCriterion("OPERID is not null");
            return (Criteria) this;
        }

        public Criteria andOperidEqualTo(String value) {
            addCriterion("OPERID =", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotEqualTo(String value) {
            addCriterion("OPERID <>", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThan(String value) {
            addCriterion("OPERID >", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThanOrEqualTo(String value) {
            addCriterion("OPERID >=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThan(String value) {
            addCriterion("OPERID <", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThanOrEqualTo(String value) {
            addCriterion("OPERID <=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLike(String value) {
            addCriterion("OPERID like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotLike(String value) {
            addCriterion("OPERID not like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidIn(List<String> values) {
            addCriterion("OPERID in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotIn(List<String> values) {
            addCriterion("OPERID not in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidBetween(String value1, String value2) {
            addCriterion("OPERID between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotBetween(String value1, String value2) {
            addCriterion("OPERID not between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNull() {
            addCriterion("DEPTID is null");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNotNull() {
            addCriterion("DEPTID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptidEqualTo(String value) {
            addCriterion("DEPTID =", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotEqualTo(String value) {
            addCriterion("DEPTID <>", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThan(String value) {
            addCriterion("DEPTID >", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThanOrEqualTo(String value) {
            addCriterion("DEPTID >=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThan(String value) {
            addCriterion("DEPTID <", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThanOrEqualTo(String value) {
            addCriterion("DEPTID <=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLike(String value) {
            addCriterion("DEPTID like", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotLike(String value) {
            addCriterion("DEPTID not like", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidIn(List<String> values) {
            addCriterion("DEPTID in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotIn(List<String> values) {
            addCriterion("DEPTID not in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidBetween(String value1, String value2) {
            addCriterion("DEPTID between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotBetween(String value1, String value2) {
            addCriterion("DEPTID not between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andOperpasswdIsNull() {
            addCriterion("OPERPASSWD is null");
            return (Criteria) this;
        }

        public Criteria andOperpasswdIsNotNull() {
            addCriterion("OPERPASSWD is not null");
            return (Criteria) this;
        }

        public Criteria andOperpasswdEqualTo(String value) {
            addCriterion("OPERPASSWD =", value, "operpasswd");
            return (Criteria) this;
        }

        public Criteria andOperpasswdNotEqualTo(String value) {
            addCriterion("OPERPASSWD <>", value, "operpasswd");
            return (Criteria) this;
        }

        public Criteria andOperpasswdGreaterThan(String value) {
            addCriterion("OPERPASSWD >", value, "operpasswd");
            return (Criteria) this;
        }

        public Criteria andOperpasswdGreaterThanOrEqualTo(String value) {
            addCriterion("OPERPASSWD >=", value, "operpasswd");
            return (Criteria) this;
        }

        public Criteria andOperpasswdLessThan(String value) {
            addCriterion("OPERPASSWD <", value, "operpasswd");
            return (Criteria) this;
        }

        public Criteria andOperpasswdLessThanOrEqualTo(String value) {
            addCriterion("OPERPASSWD <=", value, "operpasswd");
            return (Criteria) this;
        }

        public Criteria andOperpasswdLike(String value) {
            addCriterion("OPERPASSWD like", value, "operpasswd");
            return (Criteria) this;
        }

        public Criteria andOperpasswdNotLike(String value) {
            addCriterion("OPERPASSWD not like", value, "operpasswd");
            return (Criteria) this;
        }

        public Criteria andOperpasswdIn(List<String> values) {
            addCriterion("OPERPASSWD in", values, "operpasswd");
            return (Criteria) this;
        }

        public Criteria andOperpasswdNotIn(List<String> values) {
            addCriterion("OPERPASSWD not in", values, "operpasswd");
            return (Criteria) this;
        }

        public Criteria andOperpasswdBetween(String value1, String value2) {
            addCriterion("OPERPASSWD between", value1, value2, "operpasswd");
            return (Criteria) this;
        }

        public Criteria andOperpasswdNotBetween(String value1, String value2) {
            addCriterion("OPERPASSWD not between", value1, value2, "operpasswd");
            return (Criteria) this;
        }

        public Criteria andIssuperIsNull() {
            addCriterion("ISSUPER is null");
            return (Criteria) this;
        }

        public Criteria andIssuperIsNotNull() {
            addCriterion("ISSUPER is not null");
            return (Criteria) this;
        }

        public Criteria andIssuperEqualTo(String value) {
            addCriterion("ISSUPER =", value, "issuper");
            return (Criteria) this;
        }

        public Criteria andIssuperNotEqualTo(String value) {
            addCriterion("ISSUPER <>", value, "issuper");
            return (Criteria) this;
        }

        public Criteria andIssuperGreaterThan(String value) {
            addCriterion("ISSUPER >", value, "issuper");
            return (Criteria) this;
        }

        public Criteria andIssuperGreaterThanOrEqualTo(String value) {
            addCriterion("ISSUPER >=", value, "issuper");
            return (Criteria) this;
        }

        public Criteria andIssuperLessThan(String value) {
            addCriterion("ISSUPER <", value, "issuper");
            return (Criteria) this;
        }

        public Criteria andIssuperLessThanOrEqualTo(String value) {
            addCriterion("ISSUPER <=", value, "issuper");
            return (Criteria) this;
        }

        public Criteria andIssuperLike(String value) {
            addCriterion("ISSUPER like", value, "issuper");
            return (Criteria) this;
        }

        public Criteria andIssuperNotLike(String value) {
            addCriterion("ISSUPER not like", value, "issuper");
            return (Criteria) this;
        }

        public Criteria andIssuperIn(List<String> values) {
            addCriterion("ISSUPER in", values, "issuper");
            return (Criteria) this;
        }

        public Criteria andIssuperNotIn(List<String> values) {
            addCriterion("ISSUPER not in", values, "issuper");
            return (Criteria) this;
        }

        public Criteria andIssuperBetween(String value1, String value2) {
            addCriterion("ISSUPER between", value1, value2, "issuper");
            return (Criteria) this;
        }

        public Criteria andIssuperNotBetween(String value1, String value2) {
            addCriterion("ISSUPER not between", value1, value2, "issuper");
            return (Criteria) this;
        }

        public Criteria andOperdutyIsNull() {
            addCriterion("OPERDUTY is null");
            return (Criteria) this;
        }

        public Criteria andOperdutyIsNotNull() {
            addCriterion("OPERDUTY is not null");
            return (Criteria) this;
        }

        public Criteria andOperdutyEqualTo(String value) {
            addCriterion("OPERDUTY =", value, "operduty");
            return (Criteria) this;
        }

        public Criteria andOperdutyNotEqualTo(String value) {
            addCriterion("OPERDUTY <>", value, "operduty");
            return (Criteria) this;
        }

        public Criteria andOperdutyGreaterThan(String value) {
            addCriterion("OPERDUTY >", value, "operduty");
            return (Criteria) this;
        }

        public Criteria andOperdutyGreaterThanOrEqualTo(String value) {
            addCriterion("OPERDUTY >=", value, "operduty");
            return (Criteria) this;
        }

        public Criteria andOperdutyLessThan(String value) {
            addCriterion("OPERDUTY <", value, "operduty");
            return (Criteria) this;
        }

        public Criteria andOperdutyLessThanOrEqualTo(String value) {
            addCriterion("OPERDUTY <=", value, "operduty");
            return (Criteria) this;
        }

        public Criteria andOperdutyLike(String value) {
            addCriterion("OPERDUTY like", value, "operduty");
            return (Criteria) this;
        }

        public Criteria andOperdutyNotLike(String value) {
            addCriterion("OPERDUTY not like", value, "operduty");
            return (Criteria) this;
        }

        public Criteria andOperdutyIn(List<String> values) {
            addCriterion("OPERDUTY in", values, "operduty");
            return (Criteria) this;
        }

        public Criteria andOperdutyNotIn(List<String> values) {
            addCriterion("OPERDUTY not in", values, "operduty");
            return (Criteria) this;
        }

        public Criteria andOperdutyBetween(String value1, String value2) {
            addCriterion("OPERDUTY between", value1, value2, "operduty");
            return (Criteria) this;
        }

        public Criteria andOperdutyNotBetween(String value1, String value2) {
            addCriterion("OPERDUTY not between", value1, value2, "operduty");
            return (Criteria) this;
        }

        public Criteria andOpertypeIsNull() {
            addCriterion("OPERTYPE is null");
            return (Criteria) this;
        }

        public Criteria andOpertypeIsNotNull() {
            addCriterion("OPERTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOpertypeEqualTo(String value) {
            addCriterion("OPERTYPE =", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeNotEqualTo(String value) {
            addCriterion("OPERTYPE <>", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeGreaterThan(String value) {
            addCriterion("OPERTYPE >", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeGreaterThanOrEqualTo(String value) {
            addCriterion("OPERTYPE >=", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeLessThan(String value) {
            addCriterion("OPERTYPE <", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeLessThanOrEqualTo(String value) {
            addCriterion("OPERTYPE <=", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeLike(String value) {
            addCriterion("OPERTYPE like", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeNotLike(String value) {
            addCriterion("OPERTYPE not like", value, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeIn(List<String> values) {
            addCriterion("OPERTYPE in", values, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeNotIn(List<String> values) {
            addCriterion("OPERTYPE not in", values, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeBetween(String value1, String value2) {
            addCriterion("OPERTYPE between", value1, value2, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpertypeNotBetween(String value1, String value2) {
            addCriterion("OPERTYPE not between", value1, value2, "opertype");
            return (Criteria) this;
        }

        public Criteria andOpernameIsNull() {
            addCriterion("OPERNAME is null");
            return (Criteria) this;
        }

        public Criteria andOpernameIsNotNull() {
            addCriterion("OPERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andOpernameEqualTo(String value) {
            addCriterion("OPERNAME =", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotEqualTo(String value) {
            addCriterion("OPERNAME <>", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameGreaterThan(String value) {
            addCriterion("OPERNAME >", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameGreaterThanOrEqualTo(String value) {
            addCriterion("OPERNAME >=", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameLessThan(String value) {
            addCriterion("OPERNAME <", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameLessThanOrEqualTo(String value) {
            addCriterion("OPERNAME <=", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameLike(String value) {
            addCriterion("OPERNAME like", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotLike(String value) {
            addCriterion("OPERNAME not like", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameIn(List<String> values) {
            addCriterion("OPERNAME in", values, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotIn(List<String> values) {
            addCriterion("OPERNAME not in", values, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameBetween(String value1, String value2) {
            addCriterion("OPERNAME between", value1, value2, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotBetween(String value1, String value2) {
            addCriterion("OPERNAME not between", value1, value2, "opername");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("SEX =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("SEX <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("SEX >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("SEX >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("SEX <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("SEX <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("SEX like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("SEX not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("SEX in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("SEX not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andMobilephoneIsNull() {
            addCriterion("MOBILEPHONE is null");
            return (Criteria) this;
        }

        public Criteria andMobilephoneIsNotNull() {
            addCriterion("MOBILEPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andMobilephoneEqualTo(String value) {
            addCriterion("MOBILEPHONE =", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneNotEqualTo(String value) {
            addCriterion("MOBILEPHONE <>", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneGreaterThan(String value) {
            addCriterion("MOBILEPHONE >", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILEPHONE >=", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneLessThan(String value) {
            addCriterion("MOBILEPHONE <", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneLessThanOrEqualTo(String value) {
            addCriterion("MOBILEPHONE <=", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneLike(String value) {
            addCriterion("MOBILEPHONE like", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneNotLike(String value) {
            addCriterion("MOBILEPHONE not like", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneIn(List<String> values) {
            addCriterion("MOBILEPHONE in", values, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneNotIn(List<String> values) {
            addCriterion("MOBILEPHONE not in", values, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneBetween(String value1, String value2) {
            addCriterion("MOBILEPHONE between", value1, value2, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneNotBetween(String value1, String value2) {
            addCriterion("MOBILEPHONE not between", value1, value2, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andOperphoneIsNull() {
            addCriterion("OPERPHONE is null");
            return (Criteria) this;
        }

        public Criteria andOperphoneIsNotNull() {
            addCriterion("OPERPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andOperphoneEqualTo(String value) {
            addCriterion("OPERPHONE =", value, "operphone");
            return (Criteria) this;
        }

        public Criteria andOperphoneNotEqualTo(String value) {
            addCriterion("OPERPHONE <>", value, "operphone");
            return (Criteria) this;
        }

        public Criteria andOperphoneGreaterThan(String value) {
            addCriterion("OPERPHONE >", value, "operphone");
            return (Criteria) this;
        }

        public Criteria andOperphoneGreaterThanOrEqualTo(String value) {
            addCriterion("OPERPHONE >=", value, "operphone");
            return (Criteria) this;
        }

        public Criteria andOperphoneLessThan(String value) {
            addCriterion("OPERPHONE <", value, "operphone");
            return (Criteria) this;
        }

        public Criteria andOperphoneLessThanOrEqualTo(String value) {
            addCriterion("OPERPHONE <=", value, "operphone");
            return (Criteria) this;
        }

        public Criteria andOperphoneLike(String value) {
            addCriterion("OPERPHONE like", value, "operphone");
            return (Criteria) this;
        }

        public Criteria andOperphoneNotLike(String value) {
            addCriterion("OPERPHONE not like", value, "operphone");
            return (Criteria) this;
        }

        public Criteria andOperphoneIn(List<String> values) {
            addCriterion("OPERPHONE in", values, "operphone");
            return (Criteria) this;
        }

        public Criteria andOperphoneNotIn(List<String> values) {
            addCriterion("OPERPHONE not in", values, "operphone");
            return (Criteria) this;
        }

        public Criteria andOperphoneBetween(String value1, String value2) {
            addCriterion("OPERPHONE between", value1, value2, "operphone");
            return (Criteria) this;
        }

        public Criteria andOperphoneNotBetween(String value1, String value2) {
            addCriterion("OPERPHONE not between", value1, value2, "operphone");
            return (Criteria) this;
        }

        public Criteria andOtherphoneIsNull() {
            addCriterion("OTHERPHONE is null");
            return (Criteria) this;
        }

        public Criteria andOtherphoneIsNotNull() {
            addCriterion("OTHERPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andOtherphoneEqualTo(String value) {
            addCriterion("OTHERPHONE =", value, "otherphone");
            return (Criteria) this;
        }

        public Criteria andOtherphoneNotEqualTo(String value) {
            addCriterion("OTHERPHONE <>", value, "otherphone");
            return (Criteria) this;
        }

        public Criteria andOtherphoneGreaterThan(String value) {
            addCriterion("OTHERPHONE >", value, "otherphone");
            return (Criteria) this;
        }

        public Criteria andOtherphoneGreaterThanOrEqualTo(String value) {
            addCriterion("OTHERPHONE >=", value, "otherphone");
            return (Criteria) this;
        }

        public Criteria andOtherphoneLessThan(String value) {
            addCriterion("OTHERPHONE <", value, "otherphone");
            return (Criteria) this;
        }

        public Criteria andOtherphoneLessThanOrEqualTo(String value) {
            addCriterion("OTHERPHONE <=", value, "otherphone");
            return (Criteria) this;
        }

        public Criteria andOtherphoneLike(String value) {
            addCriterion("OTHERPHONE like", value, "otherphone");
            return (Criteria) this;
        }

        public Criteria andOtherphoneNotLike(String value) {
            addCriterion("OTHERPHONE not like", value, "otherphone");
            return (Criteria) this;
        }

        public Criteria andOtherphoneIn(List<String> values) {
            addCriterion("OTHERPHONE in", values, "otherphone");
            return (Criteria) this;
        }

        public Criteria andOtherphoneNotIn(List<String> values) {
            addCriterion("OTHERPHONE not in", values, "otherphone");
            return (Criteria) this;
        }

        public Criteria andOtherphoneBetween(String value1, String value2) {
            addCriterion("OTHERPHONE between", value1, value2, "otherphone");
            return (Criteria) this;
        }

        public Criteria andOtherphoneNotBetween(String value1, String value2) {
            addCriterion("OTHERPHONE not between", value1, value2, "otherphone");
            return (Criteria) this;
        }

        public Criteria andOperenabledIsNull() {
            addCriterion("OPERENABLED is null");
            return (Criteria) this;
        }

        public Criteria andOperenabledIsNotNull() {
            addCriterion("OPERENABLED is not null");
            return (Criteria) this;
        }

        public Criteria andOperenabledEqualTo(String value) {
            addCriterion("OPERENABLED =", value, "operenabled");
            return (Criteria) this;
        }

        public Criteria andOperenabledNotEqualTo(String value) {
            addCriterion("OPERENABLED <>", value, "operenabled");
            return (Criteria) this;
        }

        public Criteria andOperenabledGreaterThan(String value) {
            addCriterion("OPERENABLED >", value, "operenabled");
            return (Criteria) this;
        }

        public Criteria andOperenabledGreaterThanOrEqualTo(String value) {
            addCriterion("OPERENABLED >=", value, "operenabled");
            return (Criteria) this;
        }

        public Criteria andOperenabledLessThan(String value) {
            addCriterion("OPERENABLED <", value, "operenabled");
            return (Criteria) this;
        }

        public Criteria andOperenabledLessThanOrEqualTo(String value) {
            addCriterion("OPERENABLED <=", value, "operenabled");
            return (Criteria) this;
        }

        public Criteria andOperenabledLike(String value) {
            addCriterion("OPERENABLED like", value, "operenabled");
            return (Criteria) this;
        }

        public Criteria andOperenabledNotLike(String value) {
            addCriterion("OPERENABLED not like", value, "operenabled");
            return (Criteria) this;
        }

        public Criteria andOperenabledIn(List<String> values) {
            addCriterion("OPERENABLED in", values, "operenabled");
            return (Criteria) this;
        }

        public Criteria andOperenabledNotIn(List<String> values) {
            addCriterion("OPERENABLED not in", values, "operenabled");
            return (Criteria) this;
        }

        public Criteria andOperenabledBetween(String value1, String value2) {
            addCriterion("OPERENABLED between", value1, value2, "operenabled");
            return (Criteria) this;
        }

        public Criteria andOperenabledNotBetween(String value1, String value2) {
            addCriterion("OPERENABLED not between", value1, value2, "operenabled");
            return (Criteria) this;
        }

        public Criteria andFillstr50IsNull() {
            addCriterion("FILLSTR50 is null");
            return (Criteria) this;
        }

        public Criteria andFillstr50IsNotNull() {
            addCriterion("FILLSTR50 is not null");
            return (Criteria) this;
        }

        public Criteria andFillstr50EqualTo(String value) {
            addCriterion("FILLSTR50 =", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50NotEqualTo(String value) {
            addCriterion("FILLSTR50 <>", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50GreaterThan(String value) {
            addCriterion("FILLSTR50 >", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50GreaterThanOrEqualTo(String value) {
            addCriterion("FILLSTR50 >=", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50LessThan(String value) {
            addCriterion("FILLSTR50 <", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50LessThanOrEqualTo(String value) {
            addCriterion("FILLSTR50 <=", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50Like(String value) {
            addCriterion("FILLSTR50 like", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50NotLike(String value) {
            addCriterion("FILLSTR50 not like", value, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50In(List<String> values) {
            addCriterion("FILLSTR50 in", values, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50NotIn(List<String> values) {
            addCriterion("FILLSTR50 not in", values, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50Between(String value1, String value2) {
            addCriterion("FILLSTR50 between", value1, value2, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr50NotBetween(String value1, String value2) {
            addCriterion("FILLSTR50 not between", value1, value2, "fillstr50");
            return (Criteria) this;
        }

        public Criteria andFillstr80IsNull() {
            addCriterion("FILLSTR80 is null");
            return (Criteria) this;
        }

        public Criteria andFillstr80IsNotNull() {
            addCriterion("FILLSTR80 is not null");
            return (Criteria) this;
        }

        public Criteria andFillstr80EqualTo(String value) {
            addCriterion("FILLSTR80 =", value, "fillstr80");
            return (Criteria) this;
        }

        public Criteria andFillstr80NotEqualTo(String value) {
            addCriterion("FILLSTR80 <>", value, "fillstr80");
            return (Criteria) this;
        }

        public Criteria andFillstr80GreaterThan(String value) {
            addCriterion("FILLSTR80 >", value, "fillstr80");
            return (Criteria) this;
        }

        public Criteria andFillstr80GreaterThanOrEqualTo(String value) {
            addCriterion("FILLSTR80 >=", value, "fillstr80");
            return (Criteria) this;
        }

        public Criteria andFillstr80LessThan(String value) {
            addCriterion("FILLSTR80 <", value, "fillstr80");
            return (Criteria) this;
        }

        public Criteria andFillstr80LessThanOrEqualTo(String value) {
            addCriterion("FILLSTR80 <=", value, "fillstr80");
            return (Criteria) this;
        }

        public Criteria andFillstr80Like(String value) {
            addCriterion("FILLSTR80 like", value, "fillstr80");
            return (Criteria) this;
        }

        public Criteria andFillstr80NotLike(String value) {
            addCriterion("FILLSTR80 not like", value, "fillstr80");
            return (Criteria) this;
        }

        public Criteria andFillstr80In(List<String> values) {
            addCriterion("FILLSTR80 in", values, "fillstr80");
            return (Criteria) this;
        }

        public Criteria andFillstr80NotIn(List<String> values) {
            addCriterion("FILLSTR80 not in", values, "fillstr80");
            return (Criteria) this;
        }

        public Criteria andFillstr80Between(String value1, String value2) {
            addCriterion("FILLSTR80 between", value1, value2, "fillstr80");
            return (Criteria) this;
        }

        public Criteria andFillstr80NotBetween(String value1, String value2) {
            addCriterion("FILLSTR80 not between", value1, value2, "fillstr80");
            return (Criteria) this;
        }

        public Criteria andFillstr100IsNull() {
            addCriterion("FILLSTR100 is null");
            return (Criteria) this;
        }

        public Criteria andFillstr100IsNotNull() {
            addCriterion("FILLSTR100 is not null");
            return (Criteria) this;
        }

        public Criteria andFillstr100EqualTo(String value) {
            addCriterion("FILLSTR100 =", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100NotEqualTo(String value) {
            addCriterion("FILLSTR100 <>", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100GreaterThan(String value) {
            addCriterion("FILLSTR100 >", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100GreaterThanOrEqualTo(String value) {
            addCriterion("FILLSTR100 >=", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100LessThan(String value) {
            addCriterion("FILLSTR100 <", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100LessThanOrEqualTo(String value) {
            addCriterion("FILLSTR100 <=", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100Like(String value) {
            addCriterion("FILLSTR100 like", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100NotLike(String value) {
            addCriterion("FILLSTR100 not like", value, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100In(List<String> values) {
            addCriterion("FILLSTR100 in", values, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100NotIn(List<String> values) {
            addCriterion("FILLSTR100 not in", values, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100Between(String value1, String value2) {
            addCriterion("FILLSTR100 between", value1, value2, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr100NotBetween(String value1, String value2) {
            addCriterion("FILLSTR100 not between", value1, value2, "fillstr100");
            return (Criteria) this;
        }

        public Criteria andFillstr150IsNull() {
            addCriterion("FILLSTR150 is null");
            return (Criteria) this;
        }

        public Criteria andFillstr150IsNotNull() {
            addCriterion("FILLSTR150 is not null");
            return (Criteria) this;
        }

        public Criteria andFillstr150EqualTo(String value) {
            addCriterion("FILLSTR150 =", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150NotEqualTo(String value) {
            addCriterion("FILLSTR150 <>", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150GreaterThan(String value) {
            addCriterion("FILLSTR150 >", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150GreaterThanOrEqualTo(String value) {
            addCriterion("FILLSTR150 >=", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150LessThan(String value) {
            addCriterion("FILLSTR150 <", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150LessThanOrEqualTo(String value) {
            addCriterion("FILLSTR150 <=", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150Like(String value) {
            addCriterion("FILLSTR150 like", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150NotLike(String value) {
            addCriterion("FILLSTR150 not like", value, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150In(List<String> values) {
            addCriterion("FILLSTR150 in", values, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150NotIn(List<String> values) {
            addCriterion("FILLSTR150 not in", values, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150Between(String value1, String value2) {
            addCriterion("FILLSTR150 between", value1, value2, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr150NotBetween(String value1, String value2) {
            addCriterion("FILLSTR150 not between", value1, value2, "fillstr150");
            return (Criteria) this;
        }

        public Criteria andFillstr600IsNull() {
            addCriterion("FILLSTR600 is null");
            return (Criteria) this;
        }

        public Criteria andFillstr600IsNotNull() {
            addCriterion("FILLSTR600 is not null");
            return (Criteria) this;
        }

        public Criteria andFillstr600EqualTo(String value) {
            addCriterion("FILLSTR600 =", value, "fillstr600");
            return (Criteria) this;
        }

        public Criteria andFillstr600NotEqualTo(String value) {
            addCriterion("FILLSTR600 <>", value, "fillstr600");
            return (Criteria) this;
        }

        public Criteria andFillstr600GreaterThan(String value) {
            addCriterion("FILLSTR600 >", value, "fillstr600");
            return (Criteria) this;
        }

        public Criteria andFillstr600GreaterThanOrEqualTo(String value) {
            addCriterion("FILLSTR600 >=", value, "fillstr600");
            return (Criteria) this;
        }

        public Criteria andFillstr600LessThan(String value) {
            addCriterion("FILLSTR600 <", value, "fillstr600");
            return (Criteria) this;
        }

        public Criteria andFillstr600LessThanOrEqualTo(String value) {
            addCriterion("FILLSTR600 <=", value, "fillstr600");
            return (Criteria) this;
        }

        public Criteria andFillstr600Like(String value) {
            addCriterion("FILLSTR600 like", value, "fillstr600");
            return (Criteria) this;
        }

        public Criteria andFillstr600NotLike(String value) {
            addCriterion("FILLSTR600 not like", value, "fillstr600");
            return (Criteria) this;
        }

        public Criteria andFillstr600In(List<String> values) {
            addCriterion("FILLSTR600 in", values, "fillstr600");
            return (Criteria) this;
        }

        public Criteria andFillstr600NotIn(List<String> values) {
            addCriterion("FILLSTR600 not in", values, "fillstr600");
            return (Criteria) this;
        }

        public Criteria andFillstr600Between(String value1, String value2) {
            addCriterion("FILLSTR600 between", value1, value2, "fillstr600");
            return (Criteria) this;
        }

        public Criteria andFillstr600NotBetween(String value1, String value2) {
            addCriterion("FILLSTR600 not between", value1, value2, "fillstr600");
            return (Criteria) this;
        }

        public Criteria andFilldate1IsNull() {
            addCriterion("FILLDATE1 is null");
            return (Criteria) this;
        }

        public Criteria andFilldate1IsNotNull() {
            addCriterion("FILLDATE1 is not null");
            return (Criteria) this;
        }

        public Criteria andFilldate1EqualTo(Date value) {
            addCriterion("FILLDATE1 =", value, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1NotEqualTo(Date value) {
            addCriterion("FILLDATE1 <>", value, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1GreaterThan(Date value) {
            addCriterion("FILLDATE1 >", value, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1GreaterThanOrEqualTo(Date value) {
            addCriterion("FILLDATE1 >=", value, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1LessThan(Date value) {
            addCriterion("FILLDATE1 <", value, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1LessThanOrEqualTo(Date value) {
            addCriterion("FILLDATE1 <=", value, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1In(List<Date> values) {
            addCriterion("FILLDATE1 in", values, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1NotIn(List<Date> values) {
            addCriterion("FILLDATE1 not in", values, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1Between(Date value1, Date value2) {
            addCriterion("FILLDATE1 between", value1, value2, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate1NotBetween(Date value1, Date value2) {
            addCriterion("FILLDATE1 not between", value1, value2, "filldate1");
            return (Criteria) this;
        }

        public Criteria andFilldate2IsNull() {
            addCriterion("FILLDATE2 is null");
            return (Criteria) this;
        }

        public Criteria andFilldate2IsNotNull() {
            addCriterion("FILLDATE2 is not null");
            return (Criteria) this;
        }

        public Criteria andFilldate2EqualTo(Date value) {
            addCriterion("FILLDATE2 =", value, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2NotEqualTo(Date value) {
            addCriterion("FILLDATE2 <>", value, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2GreaterThan(Date value) {
            addCriterion("FILLDATE2 >", value, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2GreaterThanOrEqualTo(Date value) {
            addCriterion("FILLDATE2 >=", value, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2LessThan(Date value) {
            addCriterion("FILLDATE2 <", value, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2LessThanOrEqualTo(Date value) {
            addCriterion("FILLDATE2 <=", value, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2In(List<Date> values) {
            addCriterion("FILLDATE2 in", values, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2NotIn(List<Date> values) {
            addCriterion("FILLDATE2 not in", values, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2Between(Date value1, Date value2) {
            addCriterion("FILLDATE2 between", value1, value2, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate2NotBetween(Date value1, Date value2) {
            addCriterion("FILLDATE2 not between", value1, value2, "filldate2");
            return (Criteria) this;
        }

        public Criteria andFilldate3IsNull() {
            addCriterion("FILLDATE3 is null");
            return (Criteria) this;
        }

        public Criteria andFilldate3IsNotNull() {
            addCriterion("FILLDATE3 is not null");
            return (Criteria) this;
        }

        public Criteria andFilldate3EqualTo(Date value) {
            addCriterion("FILLDATE3 =", value, "filldate3");
            return (Criteria) this;
        }

        public Criteria andFilldate3NotEqualTo(Date value) {
            addCriterion("FILLDATE3 <>", value, "filldate3");
            return (Criteria) this;
        }

        public Criteria andFilldate3GreaterThan(Date value) {
            addCriterion("FILLDATE3 >", value, "filldate3");
            return (Criteria) this;
        }

        public Criteria andFilldate3GreaterThanOrEqualTo(Date value) {
            addCriterion("FILLDATE3 >=", value, "filldate3");
            return (Criteria) this;
        }

        public Criteria andFilldate3LessThan(Date value) {
            addCriterion("FILLDATE3 <", value, "filldate3");
            return (Criteria) this;
        }

        public Criteria andFilldate3LessThanOrEqualTo(Date value) {
            addCriterion("FILLDATE3 <=", value, "filldate3");
            return (Criteria) this;
        }

        public Criteria andFilldate3In(List<Date> values) {
            addCriterion("FILLDATE3 in", values, "filldate3");
            return (Criteria) this;
        }

        public Criteria andFilldate3NotIn(List<Date> values) {
            addCriterion("FILLDATE3 not in", values, "filldate3");
            return (Criteria) this;
        }

        public Criteria andFilldate3Between(Date value1, Date value2) {
            addCriterion("FILLDATE3 between", value1, value2, "filldate3");
            return (Criteria) this;
        }

        public Criteria andFilldate3NotBetween(Date value1, Date value2) {
            addCriterion("FILLDATE3 not between", value1, value2, "filldate3");
            return (Criteria) this;
        }

        public Criteria andFillint6IsNull() {
            addCriterion("FILLINT6 is null");
            return (Criteria) this;
        }

        public Criteria andFillint6IsNotNull() {
            addCriterion("FILLINT6 is not null");
            return (Criteria) this;
        }

        public Criteria andFillint6EqualTo(Integer value) {
            addCriterion("FILLINT6 =", value, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6NotEqualTo(Integer value) {
            addCriterion("FILLINT6 <>", value, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6GreaterThan(Integer value) {
            addCriterion("FILLINT6 >", value, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6GreaterThanOrEqualTo(Integer value) {
            addCriterion("FILLINT6 >=", value, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6LessThan(Integer value) {
            addCriterion("FILLINT6 <", value, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6LessThanOrEqualTo(Integer value) {
            addCriterion("FILLINT6 <=", value, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6In(List<Integer> values) {
            addCriterion("FILLINT6 in", values, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6NotIn(List<Integer> values) {
            addCriterion("FILLINT6 not in", values, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6Between(Integer value1, Integer value2) {
            addCriterion("FILLINT6 between", value1, value2, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint6NotBetween(Integer value1, Integer value2) {
            addCriterion("FILLINT6 not between", value1, value2, "fillint6");
            return (Criteria) this;
        }

        public Criteria andFillint8IsNull() {
            addCriterion("FILLINT8 is null");
            return (Criteria) this;
        }

        public Criteria andFillint8IsNotNull() {
            addCriterion("FILLINT8 is not null");
            return (Criteria) this;
        }

        public Criteria andFillint8EqualTo(Integer value) {
            addCriterion("FILLINT8 =", value, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8NotEqualTo(Integer value) {
            addCriterion("FILLINT8 <>", value, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8GreaterThan(Integer value) {
            addCriterion("FILLINT8 >", value, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8GreaterThanOrEqualTo(Integer value) {
            addCriterion("FILLINT8 >=", value, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8LessThan(Integer value) {
            addCriterion("FILLINT8 <", value, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8LessThanOrEqualTo(Integer value) {
            addCriterion("FILLINT8 <=", value, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8In(List<Integer> values) {
            addCriterion("FILLINT8 in", values, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8NotIn(List<Integer> values) {
            addCriterion("FILLINT8 not in", values, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8Between(Integer value1, Integer value2) {
            addCriterion("FILLINT8 between", value1, value2, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint8NotBetween(Integer value1, Integer value2) {
            addCriterion("FILLINT8 not between", value1, value2, "fillint8");
            return (Criteria) this;
        }

        public Criteria andFillint10IsNull() {
            addCriterion("FILLINT10 is null");
            return (Criteria) this;
        }

        public Criteria andFillint10IsNotNull() {
            addCriterion("FILLINT10 is not null");
            return (Criteria) this;
        }

        public Criteria andFillint10EqualTo(Long value) {
            addCriterion("FILLINT10 =", value, "fillint10");
            return (Criteria) this;
        }

        public Criteria andFillint10NotEqualTo(Long value) {
            addCriterion("FILLINT10 <>", value, "fillint10");
            return (Criteria) this;
        }

        public Criteria andFillint10GreaterThan(Long value) {
            addCriterion("FILLINT10 >", value, "fillint10");
            return (Criteria) this;
        }

        public Criteria andFillint10GreaterThanOrEqualTo(Long value) {
            addCriterion("FILLINT10 >=", value, "fillint10");
            return (Criteria) this;
        }

        public Criteria andFillint10LessThan(Long value) {
            addCriterion("FILLINT10 <", value, "fillint10");
            return (Criteria) this;
        }

        public Criteria andFillint10LessThanOrEqualTo(Long value) {
            addCriterion("FILLINT10 <=", value, "fillint10");
            return (Criteria) this;
        }

        public Criteria andFillint10In(List<Long> values) {
            addCriterion("FILLINT10 in", values, "fillint10");
            return (Criteria) this;
        }

        public Criteria andFillint10NotIn(List<Long> values) {
            addCriterion("FILLINT10 not in", values, "fillint10");
            return (Criteria) this;
        }

        public Criteria andFillint10Between(Long value1, Long value2) {
            addCriterion("FILLINT10 between", value1, value2, "fillint10");
            return (Criteria) this;
        }

        public Criteria andFillint10NotBetween(Long value1, Long value2) {
            addCriterion("FILLINT10 not between", value1, value2, "fillint10");
            return (Criteria) this;
        }

        public Criteria andFillint12IsNull() {
            addCriterion("FILLINT12 is null");
            return (Criteria) this;
        }

        public Criteria andFillint12IsNotNull() {
            addCriterion("FILLINT12 is not null");
            return (Criteria) this;
        }

        public Criteria andFillint12EqualTo(Long value) {
            addCriterion("FILLINT12 =", value, "fillint12");
            return (Criteria) this;
        }

        public Criteria andFillint12NotEqualTo(Long value) {
            addCriterion("FILLINT12 <>", value, "fillint12");
            return (Criteria) this;
        }

        public Criteria andFillint12GreaterThan(Long value) {
            addCriterion("FILLINT12 >", value, "fillint12");
            return (Criteria) this;
        }

        public Criteria andFillint12GreaterThanOrEqualTo(Long value) {
            addCriterion("FILLINT12 >=", value, "fillint12");
            return (Criteria) this;
        }

        public Criteria andFillint12LessThan(Long value) {
            addCriterion("FILLINT12 <", value, "fillint12");
            return (Criteria) this;
        }

        public Criteria andFillint12LessThanOrEqualTo(Long value) {
            addCriterion("FILLINT12 <=", value, "fillint12");
            return (Criteria) this;
        }

        public Criteria andFillint12In(List<Long> values) {
            addCriterion("FILLINT12 in", values, "fillint12");
            return (Criteria) this;
        }

        public Criteria andFillint12NotIn(List<Long> values) {
            addCriterion("FILLINT12 not in", values, "fillint12");
            return (Criteria) this;
        }

        public Criteria andFillint12Between(Long value1, Long value2) {
            addCriterion("FILLINT12 between", value1, value2, "fillint12");
            return (Criteria) this;
        }

        public Criteria andFillint12NotBetween(Long value1, Long value2) {
            addCriterion("FILLINT12 not between", value1, value2, "fillint12");
            return (Criteria) this;
        }

        public Criteria andFillintvarIsNull() {
            addCriterion("FILLINTVAR is null");
            return (Criteria) this;
        }

        public Criteria andFillintvarIsNotNull() {
            addCriterion("FILLINTVAR is not null");
            return (Criteria) this;
        }

        public Criteria andFillintvarEqualTo(Short value) {
            addCriterion("FILLINTVAR =", value, "fillintvar");
            return (Criteria) this;
        }

        public Criteria andFillintvarNotEqualTo(Short value) {
            addCriterion("FILLINTVAR <>", value, "fillintvar");
            return (Criteria) this;
        }

        public Criteria andFillintvarGreaterThan(Short value) {
            addCriterion("FILLINTVAR >", value, "fillintvar");
            return (Criteria) this;
        }

        public Criteria andFillintvarGreaterThanOrEqualTo(Short value) {
            addCriterion("FILLINTVAR >=", value, "fillintvar");
            return (Criteria) this;
        }

        public Criteria andFillintvarLessThan(Short value) {
            addCriterion("FILLINTVAR <", value, "fillintvar");
            return (Criteria) this;
        }

        public Criteria andFillintvarLessThanOrEqualTo(Short value) {
            addCriterion("FILLINTVAR <=", value, "fillintvar");
            return (Criteria) this;
        }

        public Criteria andFillintvarIn(List<Short> values) {
            addCriterion("FILLINTVAR in", values, "fillintvar");
            return (Criteria) this;
        }

        public Criteria andFillintvarNotIn(List<Short> values) {
            addCriterion("FILLINTVAR not in", values, "fillintvar");
            return (Criteria) this;
        }

        public Criteria andFillintvarBetween(Short value1, Short value2) {
            addCriterion("FILLINTVAR between", value1, value2, "fillintvar");
            return (Criteria) this;
        }

        public Criteria andFillintvarNotBetween(Short value1, Short value2) {
            addCriterion("FILLINTVAR not between", value1, value2, "fillintvar");
            return (Criteria) this;
        }

        public Criteria andFilldbl1IsNull() {
            addCriterion("FILLDBL1 is null");
            return (Criteria) this;
        }

        public Criteria andFilldbl1IsNotNull() {
            addCriterion("FILLDBL1 is not null");
            return (Criteria) this;
        }

        public Criteria andFilldbl1EqualTo(BigDecimal value) {
            addCriterion("FILLDBL1 =", value, "filldbl1");
            return (Criteria) this;
        }

        public Criteria andFilldbl1NotEqualTo(BigDecimal value) {
            addCriterion("FILLDBL1 <>", value, "filldbl1");
            return (Criteria) this;
        }

        public Criteria andFilldbl1GreaterThan(BigDecimal value) {
            addCriterion("FILLDBL1 >", value, "filldbl1");
            return (Criteria) this;
        }

        public Criteria andFilldbl1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL1 >=", value, "filldbl1");
            return (Criteria) this;
        }

        public Criteria andFilldbl1LessThan(BigDecimal value) {
            addCriterion("FILLDBL1 <", value, "filldbl1");
            return (Criteria) this;
        }

        public Criteria andFilldbl1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL1 <=", value, "filldbl1");
            return (Criteria) this;
        }

        public Criteria andFilldbl1In(List<BigDecimal> values) {
            addCriterion("FILLDBL1 in", values, "filldbl1");
            return (Criteria) this;
        }

        public Criteria andFilldbl1NotIn(List<BigDecimal> values) {
            addCriterion("FILLDBL1 not in", values, "filldbl1");
            return (Criteria) this;
        }

        public Criteria andFilldbl1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL1 between", value1, value2, "filldbl1");
            return (Criteria) this;
        }

        public Criteria andFilldbl1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL1 not between", value1, value2, "filldbl1");
            return (Criteria) this;
        }

        public Criteria andFilldbl2IsNull() {
            addCriterion("FILLDBL2 is null");
            return (Criteria) this;
        }

        public Criteria andFilldbl2IsNotNull() {
            addCriterion("FILLDBL2 is not null");
            return (Criteria) this;
        }

        public Criteria andFilldbl2EqualTo(BigDecimal value) {
            addCriterion("FILLDBL2 =", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2NotEqualTo(BigDecimal value) {
            addCriterion("FILLDBL2 <>", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2GreaterThan(BigDecimal value) {
            addCriterion("FILLDBL2 >", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL2 >=", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2LessThan(BigDecimal value) {
            addCriterion("FILLDBL2 <", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL2 <=", value, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2In(List<BigDecimal> values) {
            addCriterion("FILLDBL2 in", values, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2NotIn(List<BigDecimal> values) {
            addCriterion("FILLDBL2 not in", values, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL2 between", value1, value2, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL2 not between", value1, value2, "filldbl2");
            return (Criteria) this;
        }

        public Criteria andFilldbl3IsNull() {
            addCriterion("FILLDBL3 is null");
            return (Criteria) this;
        }

        public Criteria andFilldbl3IsNotNull() {
            addCriterion("FILLDBL3 is not null");
            return (Criteria) this;
        }

        public Criteria andFilldbl3EqualTo(BigDecimal value) {
            addCriterion("FILLDBL3 =", value, "filldbl3");
            return (Criteria) this;
        }

        public Criteria andFilldbl3NotEqualTo(BigDecimal value) {
            addCriterion("FILLDBL3 <>", value, "filldbl3");
            return (Criteria) this;
        }

        public Criteria andFilldbl3GreaterThan(BigDecimal value) {
            addCriterion("FILLDBL3 >", value, "filldbl3");
            return (Criteria) this;
        }

        public Criteria andFilldbl3GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL3 >=", value, "filldbl3");
            return (Criteria) this;
        }

        public Criteria andFilldbl3LessThan(BigDecimal value) {
            addCriterion("FILLDBL3 <", value, "filldbl3");
            return (Criteria) this;
        }

        public Criteria andFilldbl3LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FILLDBL3 <=", value, "filldbl3");
            return (Criteria) this;
        }

        public Criteria andFilldbl3In(List<BigDecimal> values) {
            addCriterion("FILLDBL3 in", values, "filldbl3");
            return (Criteria) this;
        }

        public Criteria andFilldbl3NotIn(List<BigDecimal> values) {
            addCriterion("FILLDBL3 not in", values, "filldbl3");
            return (Criteria) this;
        }

        public Criteria andFilldbl3Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL3 between", value1, value2, "filldbl3");
            return (Criteria) this;
        }

        public Criteria andFilldbl3NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILLDBL3 not between", value1, value2, "filldbl3");
            return (Criteria) this;
        }

        public Criteria andUserguidIsNull() {
            addCriterion("USERGUID is null");
            return (Criteria) this;
        }

        public Criteria andUserguidIsNotNull() {
            addCriterion("USERGUID is not null");
            return (Criteria) this;
        }

        public Criteria andUserguidEqualTo(String value) {
            addCriterion("USERGUID =", value, "userguid");
            return (Criteria) this;
        }

        public Criteria andUserguidNotEqualTo(String value) {
            addCriterion("USERGUID <>", value, "userguid");
            return (Criteria) this;
        }

        public Criteria andUserguidGreaterThan(String value) {
            addCriterion("USERGUID >", value, "userguid");
            return (Criteria) this;
        }

        public Criteria andUserguidGreaterThanOrEqualTo(String value) {
            addCriterion("USERGUID >=", value, "userguid");
            return (Criteria) this;
        }

        public Criteria andUserguidLessThan(String value) {
            addCriterion("USERGUID <", value, "userguid");
            return (Criteria) this;
        }

        public Criteria andUserguidLessThanOrEqualTo(String value) {
            addCriterion("USERGUID <=", value, "userguid");
            return (Criteria) this;
        }

        public Criteria andUserguidLike(String value) {
            addCriterion("USERGUID like", value, "userguid");
            return (Criteria) this;
        }

        public Criteria andUserguidNotLike(String value) {
            addCriterion("USERGUID not like", value, "userguid");
            return (Criteria) this;
        }

        public Criteria andUserguidIn(List<String> values) {
            addCriterion("USERGUID in", values, "userguid");
            return (Criteria) this;
        }

        public Criteria andUserguidNotIn(List<String> values) {
            addCriterion("USERGUID not in", values, "userguid");
            return (Criteria) this;
        }

        public Criteria andUserguidBetween(String value1, String value2) {
            addCriterion("USERGUID between", value1, value2, "userguid");
            return (Criteria) this;
        }

        public Criteria andUserguidNotBetween(String value1, String value2) {
            addCriterion("USERGUID not between", value1, value2, "userguid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PTOPER
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 23 18:13:29 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PTOPER
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}