package skyline.platform.repository.model;

public class Ptresource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTRESOURCE.RESID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String resid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTRESOURCE.PARENTRESID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String parentresid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTRESOURCE.RESNAME
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String resname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTRESOURCE.RESTYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String restype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTRESOURCE.RESENABLED
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String resenabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTRESOURCE.RESDESC
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    private String resdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTRESOURCE.RESID
     *
     * @return the value of PTRESOURCE.RESID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getResid() {
        return resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTRESOURCE.RESID
     *
     * @param resid the value for PTRESOURCE.RESID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setResid(String resid) {
        this.resid = resid == null ? null : resid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTRESOURCE.PARENTRESID
     *
     * @return the value of PTRESOURCE.PARENTRESID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getParentresid() {
        return parentresid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTRESOURCE.PARENTRESID
     *
     * @param parentresid the value for PTRESOURCE.PARENTRESID
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setParentresid(String parentresid) {
        this.parentresid = parentresid == null ? null : parentresid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTRESOURCE.RESNAME
     *
     * @return the value of PTRESOURCE.RESNAME
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getResname() {
        return resname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTRESOURCE.RESNAME
     *
     * @param resname the value for PTRESOURCE.RESNAME
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setResname(String resname) {
        this.resname = resname == null ? null : resname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTRESOURCE.RESTYPE
     *
     * @return the value of PTRESOURCE.RESTYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getRestype() {
        return restype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTRESOURCE.RESTYPE
     *
     * @param restype the value for PTRESOURCE.RESTYPE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setRestype(String restype) {
        this.restype = restype == null ? null : restype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTRESOURCE.RESENABLED
     *
     * @return the value of PTRESOURCE.RESENABLED
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getResenabled() {
        return resenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTRESOURCE.RESENABLED
     *
     * @param resenabled the value for PTRESOURCE.RESENABLED
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setResenabled(String resenabled) {
        this.resenabled = resenabled == null ? null : resenabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTRESOURCE.RESDESC
     *
     * @return the value of PTRESOURCE.RESDESC
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public String getResdesc() {
        return resdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTRESOURCE.RESDESC
     *
     * @param resdesc the value for PTRESOURCE.RESDESC
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    public void setResdesc(String resdesc) {
        this.resdesc = resdesc == null ? null : resdesc.trim();
    }
}