package skyline.platform.repository.model;

public class Ptroleres {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTROLERES.RESID
     *
     * @mbggenerated Thu Jun 25 16:34:20 CST 2015
     */
    private String resid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PTROLERES.ROLEID
     *
     * @mbggenerated Thu Jun 25 16:34:20 CST 2015
     */
    private String roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTROLERES.RESID
     *
     * @return the value of PTROLERES.RESID
     *
     * @mbggenerated Thu Jun 25 16:34:20 CST 2015
     */
    public String getResid() {
        return resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTROLERES.RESID
     *
     * @param resid the value for PTROLERES.RESID
     *
     * @mbggenerated Thu Jun 25 16:34:20 CST 2015
     */
    public void setResid(String resid) {
        this.resid = resid == null ? null : resid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PTROLERES.ROLEID
     *
     * @return the value of PTROLERES.ROLEID
     *
     * @mbggenerated Thu Jun 25 16:34:20 CST 2015
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PTROLERES.ROLEID
     *
     * @param roleid the value for PTROLERES.ROLEID
     *
     * @mbggenerated Thu Jun 25 16:34:20 CST 2015
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }
}