package skyline.platform.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.platform.repository.model.Ptlogicact;
import skyline.platform.repository.model.PtlogicactExample;

public interface PtlogicactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    int countByExample(PtlogicactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    int deleteByExample(PtlogicactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    int insert(Ptlogicact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    int insertSelective(Ptlogicact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    List<Ptlogicact> selectByExample(PtlogicactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    int updateByExampleSelective(@Param("record") Ptlogicact record, @Param("example") PtlogicactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTLOGICACT
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    int updateByExample(@Param("record") Ptlogicact record, @Param("example") PtlogicactExample example);
}