package skyline.platform.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.platform.repository.model.Ptoperrole;
import skyline.platform.repository.model.PtoperroleExample;

public interface PtoperroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPERROLE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    int countByExample(PtoperroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPERROLE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    int deleteByExample(PtoperroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPERROLE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    int insert(Ptoperrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPERROLE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    int insertSelective(Ptoperrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPERROLE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    List<Ptoperrole> selectByExample(PtoperroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPERROLE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    int updateByExampleSelective(@Param("record") Ptoperrole record, @Param("example") PtoperroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPERROLE
     *
     * @mbggenerated Tue Jun 23 18:13:29 CST 2015
     */
    int updateByExample(@Param("record") Ptoperrole record, @Param("example") PtoperroleExample example);
}